/**
 * \file hsphy.c
 * \brief Functions to interface to the HSPHY
 *
 * \version see header file
 * \copyright Copyright (c) 2019-2020 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#include <stdio.h>
#include "types.h"
#include "hsphy.h"
#include "eth_phy.h"
#include "board_cfg.h"

static boolean g_hsphyInitDone_b[HSPHY_NUMBER_OF_PORTS] = {FALSE, FALSE};

sint32 HSPHY_Enable(void)
{
    if (IfxHsphy_enableModule(&MODULE_HSPHY) == TRUE)
    {
        return SUCCESS;
    }

    return FAILURE;
}

sint32 HSPHY_Init_MP8G_Phy_Instance(HSPHY_MP8G_CTRL_t const *MP8G_PHY_p)
{

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_Mdio(const uint8 phyIdx_u8, const IfxGeth_Mdio_InOut *mdio_p)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[phyIdx_u8].B.MDIO = mdio_p->inSelect;
    regs->ETH[phyIdx_u8].B.MDIOEN = 1;

    return SUCCESS;
}


sint32 HSPHY_Init_Ethernet_Mdio0(IfxGeth_Mdio_InOut mdio)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[0].B.MDIO = mdio.inSelect;
    regs->ETH[0].B.MDIOEN = 1;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_Mdio1(IfxGeth_Mdio_InOut mdio)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[1].B.MDIO = mdio.inSelect;
    regs->ETH[1].B.MDIOEN = 1;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_Crs(const uint8 mdioIdx_u8, IfxGeth_Crs_In const *crs)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[mdioIdx_u8].B.CRS = crs->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_Col(const uint8 ethIdx_u8, IfxGeth_Col_In const *col)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.COL = col->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxCtl(const uint8 ethIdx_u8, IfxGeth_Rxctl_In const *rxctl)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXCTL = rxctl->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxD0(const uint8 ethIdx_u8, IfxGeth_Rxd_In const *rxd0)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXD0 = rxd0->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxD1(const uint8 ethIdx_u8, IfxGeth_Rxd_In const *rxd1)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXD1 = rxd1->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxD2(const uint8 ethIdx_u8, IfxGeth_Rxd_In const *rxd2)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXD2 = rxd2->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxD3(const uint8 ethIdx_u8, IfxGeth_Rxd_In const *rxd3)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXD3 = rxd3->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_TxClk(const uint8 ethIdx_u8, IfxGeth_Txclk_Out const *txclk)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.TXCLK = txclk->select;

    return SUCCESS;
}

sint32 HSPHY_Init_Ethernet_RxClk(const uint8 ethIdx_u8, IfxGeth_Rxclk_In const *rxclk)
{
    Ifx_HSPHY *const regs = &MODULE_HSPHY;

    regs->ETH[ethIdx_u8].B.RXCLK = rxclk->select;

    return SUCCESS;
}

sint32 HSPHY_PhyReg_read(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, const uint16 regAddr_u16, uint16 *const regData_u16_p, uint32 timeOut_u32)
{
    Ifx_HSPHY_PHYREG_CTRL phyctrl;

    if ((hsphyInstance_p == NULL) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    while ((hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.B.ACT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    phyctrl.B.ADDR = regAddr_u16;
    phyctrl.B.TYP = 1; /* 1 = read, 2 = write */
    phyctrl.B.ACT = 1;
    hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.U = phyctrl.U;

    while ((hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.B.ACT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    *regData_u16_p = hsphyInstance_p->PHYREG[phyIdx_u8].DATA.B.DATA;

    return SUCCESS;
}

sint32 HSPHY_PhyReg_write(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, const uint16 regAddr_u16, const uint16 regData_u16, uint32 timeOut_u32)
{
    Ifx_HSPHY_PHYREG_CTRL phyctrl;

    if ((hsphyInstance_p == NULL) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    while ((hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.B.ACT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    phyctrl.B.ADDR = regAddr_u16;
    phyctrl.B.TYP = 2; /* 1 = read, 2 = write */
    phyctrl.B.ACT = 1;
    hsphyInstance_p->PHYREG[phyIdx_u8].DATA.B.DATA = regData_u16;

    hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.U = phyctrl.U;
    while ((hsphyInstance_p->PHYREG[phyIdx_u8].CTRL.B.ACT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    return SUCCESS;
}

sint32 HSPHY_100M_Mode_Init(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, uint32 timeOut_u32)
{
    if ((hsphyInstance_p == NULL) || (phyIdx_u8 >= HSPHY_NUMBER_OF_PORTS) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    if (g_hsphyInitDone_b[phyIdx_u8] == TRUE)
    {
        return SUCCESS;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.PWRDWN = 0;
    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.RST = 0;

    /* USXGMII / SerialGMII Internal PHY (data clocks generated on Chip) is selected */
    hsphyInstance_p->ETH[phyIdx_u8].B.EPR = IfxHsphy_EthCtrlExtPhySel_usxgmii;

    while ((hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.INITDONE == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.EXTLDDONE = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.INIT_DN == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.EXT_LD_DN = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.B.RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_MPLLA_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_CLK_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_RANGE = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_USE_PAD = 0;

    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 1a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 0;
    /* Step 1b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 1c */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 2 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 1;

    /* Step 3 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL2.B.PCS_TYPE_SEL = 0x1; /* 0001: Select 10GBASE-X PCS Type */

    /* Step 4 */
    /* 100M mode, SS6=0, SS13=1 */
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS6 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS13 = 1;

    /* Step 5 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 0;

    /* Step 6a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL0.B.MPLLA_MULTIPLIER = 50;       /* 50: 25MHz, 125: 40MHz, 100: 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_TX_CLK_DIV = 1;        /* 0 = 40/100MHz, 1 = 25MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_DIV16P5_CLK_EN = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL6.B.CP_PROP = 5;                      /* 5 = 25MHz, 6 = 40MHz, 6 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL7.B.CP_PROP_GS = 10;                  /* 10 = 25MHz, 12 = 40MHz, 12 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_MPLLA_CTRL1.B.MPLLA_FRACN_CTRL = 0;            /* 0 = 25/100MHz, 260 = 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_VCO_CAL_LD0.B.VCO_LD_VAL_0 = 1000;     /* 1000: 25/100MHz, 1016: 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_VCO_CAL_REF0.B.VCO_REF_LD_0 = 10;              /* 10 = 25Mhz, 16 = 40MHz, 20 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_MISC_CTRL2.B.SUP_MISC = 1;                 /* 1 = 25/40MHz, 2 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_DIV16P5_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_GENCTRL4.B.RX_125MHZ_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_CDR_CTRL.B.CDR_TRACK_EN_0 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_RATE_CTRL.B.TX0_RATE = 2;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_RATE_CTRL.B.RX0_RATE = 2;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_MISC_CTRL0.B.RX0_MISC = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_BOOST_CTRL.B.TX0_IBOOST = 15;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.VBOOST_EN_0 = 0;
    /* Step 6b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 1;
    /* Step 6c */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6d */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6e */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6f */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_STS.B.RX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 7 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 8 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 0;
    /* Step 9, set LPM = 1 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_LEN << IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_OFF;
    /* Step 10 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 6) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 11, clear LPM = 0, keep RST = 0 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = 0;
    /* Step 12 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 4) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 13 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 1;

    g_hsphyInitDone_b[phyIdx_u8] = TRUE;

    return SUCCESS;
}

sint32 HSPHY_1G_Mode_Init(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, uint32 timeOut_u32)
{
    if ((hsphyInstance_p == NULL) || (phyIdx_u8 >= HSPHY_NUMBER_OF_PORTS) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    if (g_hsphyInitDone_b[phyIdx_u8] == TRUE)
    {
        return SUCCESS;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.PWRDWN = 0;
    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.RST = 0;

    /* USXGMII / SerialGMII Internal PHY (data clocks generated on Chip) is selected */
    hsphyInstance_p->ETH[phyIdx_u8].B.EPR = IfxHsphy_EthCtrlExtPhySel_usxgmii;

    while ((hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.INITDONE == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.EXTLDDONE = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.INIT_DN == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.EXT_LD_DN = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.B.RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_MPLLA_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_CLK_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_RANGE = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_USE_PAD = 0;

    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 1a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 0;

    /* Step 1b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 1c */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 2 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 1;

    /* Step 3 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL2.B.PCS_TYPE_SEL = 0x1; /* 0001: Select 10GBASE-X PCS Type */

    /* Step 4 */
    /* 1G mode, SS6=1, SS13=0 */
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS6 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS13 = 0;

    /* Step 5 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 0;

    /* Step 6a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL0.B.MPLLA_MULTIPLIER = 50;       /* 50: 25MHz, 125: 40MHz, 100: 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_TX_CLK_DIV = 1;        /* 0 = 40/100MHz, 1 = 25MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_DIV16P5_CLK_EN = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL6.B.CP_PROP = 5;                      /* 5 = 25MHz, 6 = 40MHz, 6 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL7.B.CP_PROP_GS = 10;                  /* 10 = 25MHz, 12 = 40MHz, 12 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_MPLLA_CTRL1.B.MPLLA_FRACN_CTRL = 0;            /* 0 = 25/100MHz, 260 = 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_VCO_CAL_LD0.B.VCO_LD_VAL_0 = 1000;     /* 1000: 25/100MHz, 1016: 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_VCO_CAL_REF0.B.VCO_REF_LD_0 = 10;              /* 10 = 25Mhz, 16 = 40MHz, 20 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_MISC_CTRL2.B.SUP_MISC = 1;                 /* 1 = 25/40MHz, 2 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_DIV16P5_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_GENCTRL4.B.RX_125MHZ_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_RATE_CTRL.B.TX0_RATE = 2;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_RATE_CTRL.B.RX0_RATE = 2;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_MISC_CTRL0.B.RX0_MISC = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_BOOST_CTRL.B.TX0_IBOOST = 15;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.VBOOST_EN_0 = 0;
    /* Step 6b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 1;
    /* Step 6c */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6d */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6e */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6f */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_STS.B.RX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 7 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 8 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 0;
    /* Step 9, set LPM = 1 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = 0x0800;// IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_LEN << IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_OFF;
    /* Step 10 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 6) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 11, clear LPM = 0, keep RST = 0 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = 0;
    /* Step 12 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 4) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 13 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 1;

    g_hsphyInitDone_b[phyIdx_u8] = TRUE;

    return SUCCESS;
}

sint32 HSPHY_2G5_Mode_Init(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, uint32 timeOut_u32)
{
    if ((hsphyInstance_p == NULL) || (phyIdx_u8 >= HSPHY_NUMBER_OF_PORTS) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    if (g_hsphyInitDone_b[phyIdx_u8] == TRUE)
    {
        return SUCCESS;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.PWRDWN = 0;
    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.RST = 0;

    /* USXGMII / SerialGMII Internal PHY (data clocks generated on Chip) is selected */
    hsphyInstance_p->ETH[phyIdx_u8].B.EPR = IfxHsphy_EthCtrlExtPhySel_usxgmii;

    while ((hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.INITDONE == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.EXTLDDONE = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.INIT_DN == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.EXT_LD_DN = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.B.RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_MPLLA_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_CLK_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_RANGE = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_USE_PAD = 0;

    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 1a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 0;
    /* Step 1b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 1c */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 2 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 1;

    /* Step 3 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL2.B.PCS_TYPE_SEL = 0x1; /* 0001: Select 10GBASE-X PCS Type */

    /* Step 4 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.EN_2_5G_MODE = 1;

    /* Step 5 */
    /* 2.5G mode, SS6=1, SS13=0 */
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS6 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS13 = 0;

    /* Step 6 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_RST_0 = 0;

    /* Step 7a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL0.B.MPLLA_MULTIPLIER = 125;      /* 39: 40MHz, 125: 25/100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_TX_CLK_DIV = 0;        /* 0 = 25/100MHz, 1 = 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_DIV16P5_CLK_EN = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL6.B.CP_PROP = 5;                      /* 4 = 40MHz, 5 = 25MHz, 7 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL7.B.CP_PROP_GS = 10;                  /* 8 = 40MHz, 10 = 25MHz, 14 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_MPLLA_CTRL1.B.MPLLA_FRACN_CTRL = 0;            /* 0 = 25/100MHz, 260 = 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_VCO_CAL_LD0.B.VCO_LD_VAL_0 = 1000;     /* 1000: 25/100MHz, 1016: 40MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_VCO_CAL_REF0.B.VCO_REF_LD_0 = 8;               /* 8 = 25Mhz, 13 = 40MHz, 16 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_MISC_CTRL2.B.SUP_MISC = 1;                 /* 1 = 25/40MHz, 2 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_DIV16P5_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_GENCTRL4.B.RX_125MHZ_CLK_EN_0 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_RATE_CTRL.B.TX0_RATE = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_RATE_CTRL.B.RX0_RATE = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_MISC_CTRL0.B.RX0_MISC = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX0_WIDTH = 1; /* 10bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_BOOST_CTRL.B.TX0_IBOOST = 15;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.VBOOST_EN_0 = 0;
    /* Step 7b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 1;
    /* Step 7c */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 7d */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 7e */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 7f */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_STS.B.RX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 8 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 9 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 0;
    /* Step 10, set LPM = 1 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_LEN << IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_OFF;
    /* Step 11 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 6) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 12, clear LPM = 0, keep RST = 0 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = 0;
    /* Step 13 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 4) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 14 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 1;

//	hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DEBUG_CTRL.B.TX_PMBL_CTL = 1;//Jrra #355

    g_hsphyInitDone_b[phyIdx_u8] = TRUE;

    return SUCCESS;
}

sint32 HSPHY_5G_Mode_Init(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, uint32 timeOut_u32)
{
    if ((hsphyInstance_p == NULL) || (phyIdx_u8 >= HSPHY_NUMBER_OF_PORTS) || (timeOut_u32 == 0))
    {
        return FAILURE;
    }

    if (g_hsphyInitDone_b[phyIdx_u8] == TRUE)
    {
        return SUCCESS;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.PWRDWN = 0;
    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.RST = 0;

    /* USXGMII / SerialGMII Internal PHY (data clocks generated on Chip) is selected */
    hsphyInstance_p->ETH[phyIdx_u8].B.EPR = IfxHsphy_EthCtrlExtPhySel_usxgmii;

    while ((hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.INITDONE == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->PHY[phyIdx_u8].CTRL1.B.EXTLDDONE = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.INIT_DN == 0) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_SRAM.B.EXT_LD_DN = 1;

    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.B.RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_MPLLA_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_CLK_DIV2 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_RANGE = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_REF_CLK_CTRL.B.REF_USE_PAD = 0;

    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.VR_RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 1a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 0;
    /* Step 1b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 1c */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 2 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.USXG_EN = 1;
    /* Step 3 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_KR_CTRL.B.USXG_MODE = 1; /* 5G USXGMII */

    /* Step 4a */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL0.B.MPLLA_MULTIPLIER = 103;       /* 50: 25MHz, 125: 40MHz, 100: 100MHz, 103: 25MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_TX_CLK_DIV = 3;        /* 0 = 40/100MHz, 1 = 25MHz, 3 = ? */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_MPLLA_CTRL2.B.MPLLA_DIV16P5_CLK_EN = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL6.B.CP_PROP = 5;                      /* 5 = 25MHz, 6 = 40MHz, 6 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_8G_MPLLA_CTRL7.B.CP_PROP_GS = 10;                  /* 10 = 25MHz, 12 = 40MHz, 12 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_MPLLA_CTRL1.B.MPLLA_FRACN_CTRL = 390;          /* 0 = 25/100MHz, 260 = 40MHz, 390 = 25 MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_VCO_CAL_LD0.B.VCO_LD_VAL_0 = 1031;     /* 1000: 25/100MHz, 1016: 40MHz, 1031 = ? */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_VCO_CAL_REF0.B.VCO_REF_LD_0 = 10;              /* 10 = 25Mhz, 16 = 40MHz, 20 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_MISC_CTRL2.B.SUP_MISC = 1;                 /* 1 = 25/40MHz, 2 = 100MHz */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_GENCTRL1.B.RX_DIV16P5_CLK_EN_0 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_GENCTRL4.B.RX_125MHZ_CLK_EN_0 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_RATE_CTRL.B.TX0_RATE = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_RATE_CTRL.B.RX0_RATE = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_16G_25G_RX_MISC_CTRL0.B.RX0_MISC = 3;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX0_WIDTH = 3; /* 20bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX0_WIDTH = 3; /* 20bit */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_BOOST_CTRL.B.TX0_IBOOST = 12;
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.VBOOST_EN_0 = 1;
    /* Step 4b */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_MPLL_CMN_CTRL.B.MPLL_EN_0 = 1;
    /* Step 4c */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_TX_GENCTRL2.B.TX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 4d */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_STS.B.TX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 4e */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_RX_GENCTRL2.B.RX_REQ_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 4f */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_RX_STS.B.RX_ACK_0 == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    /* Step 5 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.INIT == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 6 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 0;
    /* Step 7, set LPM = 1 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_LEN << IFX_HSPHY_XPCS_PCS_SR_XS_CTRL1_LPM_OFF;
    /* Step 8 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 6) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 9, clear LPM = 0, keep RST = 0 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.SR_XS_CTRL1.U = 0;
    /* Step 10 */
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_STS.B.PSEQ_STATE != 4) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }
    /* Step 11 */
    hsphyInstance_p->XPCS[phyIdx_u8].PMA.VR_XS_MP_12G_16G_25G_TX_GENCTRL1.B.TX_CLK_RDY_0 = 1;

    /* Step 12 */
    /* 5G mode, SS5=1, SS6=0, SS13=1 */
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS5 = 1;
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS6 = 0;
    hsphyInstance_p->XPCS[phyIdx_u8].MII.CTRL.B.SS13 = 1;

    /* Step 13 */
    /* wait > 100ns for clock to stabilize, tbd. */

    /* Step 14 */
    hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.USRA_RST = 1;
    while ((hsphyInstance_p->XPCS[phyIdx_u8].PCS.VR_XS_DIG_CTRL1.B.USRA_RST == 1) && (timeOut_u32 > 0))
    {
        timeOut_u32--;
    }
    if (timeOut_u32 == 0)
    {
        return FAILURE;
    }

    g_hsphyInitDone_b[phyIdx_u8] = TRUE;

    return SUCCESS;
}

sint32 HSPHY_Init_Mode(Ifx_HSPHY *const hsphyInstance_p, const uint8 phyIdx_u8, const uint16 speed_u16)
{
    if (speed_u16 == ETH_PHY_LINK_SPEED_5000M)
    {
        if (HSPHY_5G_Mode_Init(&MODULE_HSPHY, 0, 0xFFFFF) == SUCCESS)
        {
            printf("Phy%i: HSPHY_5G_Mode_Init() = SUCCESS"EOL, 0);
        }
        else
        {
            printf("Phy%i: HSPHY_5G_Mode_Init() = FAIL"EOL, 0);
            return FAILURE;
        }

        if (phyIdx_u8 == 1)
        {
            if (HSPHY_5G_Mode_Init(hsphyInstance_p, phyIdx_u8, 0xFFFFF) == SUCCESS)
            {
                printf("Phy%i: HSPHY_5G_Mode_Init() = SUCCESS"EOL, phyIdx_u8);
            }
            else
            {
                printf("Phy%i: HSPHY_5G_Mode_Init() = FAIL"EOL, phyIdx_u8);
                return FAILURE;
            }
        }
    }
    else if (speed_u16 == ETH_PHY_LINK_SPEED_2500M)
    {
        if (HSPHY_2G5_Mode_Init(hsphyInstance_p, 0, 0xFFFFF) == SUCCESS)
        {
            printf("Phy%i: HSPHY_2G5_Mode_Init() = SUCCESS"EOL, 0);
        }
        else
        {
            printf("Phy%i: HSPHY_2G5_Mode_Init() = FAIL"EOL, 0);
            return FAILURE;
        }

        if (phyIdx_u8 == 1)
        {
            if (HSPHY_2G5_Mode_Init(hsphyInstance_p, phyIdx_u8, 0xFFFFF) == SUCCESS)
            {
                printf("Phy%i: HSPHY_2G5_Mode_Init() = SUCCESS"EOL, phyIdx_u8);
            }
            else
            {
                printf("Phy%i: HSPHY_2G5_Mode_Init() = FAIL"EOL, phyIdx_u8);
                return FAILURE;
            }
        }
    }
    else if (speed_u16 == ETH_PHY_LINK_SPEED_1000M)
    {
        if (HSPHY_1G_Mode_Init(hsphyInstance_p, 0, 0xFFFFF) == SUCCESS)
        {
            printf("Phy%i: HSPHY_1G_Mode_Init() = SUCCESS"EOL, 0);
        }
        else
        {
            printf("Phy%i: HSPHY_1G_Mode_Init() = FAIL"EOL, 0);
            return FAILURE;
        }

        if (phyIdx_u8 == 1)
        {
            if (HSPHY_1G_Mode_Init(&MODULE_HSPHY, phyIdx_u8, 0xFFFFF) == SUCCESS)
            {
                printf("Phy%i: HSPHY_1G_Mode_Init() = SUCCESS"EOL, phyIdx_u8);
            }
            else
            {
                printf("Phy%i: HSPHY_1G_Mode_Init() = FAIL"EOL, phyIdx_u8);
                return FAILURE;
            }
        }
    }
    else
    {
        /* ETH_PHY_LINK_SPEED_100M */
        if (HSPHY_100M_Mode_Init(&MODULE_HSPHY, 0, 0xFFFFF) == SUCCESS)
        {
            printf("Phy%i: HSPHY_100M_Mode_Init() = SUCCESS"EOL, 0);
        }
        else
        {
            printf("Phy%i: HSPHY_100M_Mode_Init() = FAIL"EOL, 0);
            return FAILURE;
        }

        if (phyIdx_u8 == 1)
        {
            if (HSPHY_100M_Mode_Init(&MODULE_HSPHY, phyIdx_u8, 0xFFFFF) == SUCCESS)
            {
                printf("Phy%i: HSPHY_100M_Mode_Init() = SUCCESS"EOL, phyIdx_u8);
            }
            else
            {
                printf("Phy%i: HSPHY_100M_Mode_Init() = FAIL"EOL, phyIdx_u8);
                return FAILURE;
            }
        }
    }

    return SUCCESS;
}

void Board_Hsphy_Mp8G_SetMuxToEth(void)
{
    IfxPort_setPinHigh(HSPHY_MP8G_BOARD_MUX.port, HSPHY_MP8G_BOARD_MUX.pinIndex);
    IfxPort_setPinModeOutput(HSPHY_MP8G_BOARD_MUX.port, HSPHY_MP8G_BOARD_MUX.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

void Board_Hsphy_Mp8G_SetMuxToPcie(void)
{
    IfxPort_setPinLow(HSPHY_MP8G_BOARD_MUX.port, HSPHY_MP8G_BOARD_MUX.pinIndex);
    IfxPort_setPinModeOutput(HSPHY_MP8G_BOARD_MUX.port, HSPHY_MP8G_BOARD_MUX.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}
