/**********************************************************************************************************************
 * \file I2C_Read_Ext_Device.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxI2c_I2c.h"
#include "Bsp.h"
#include "I2C_EEPROM.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* EEPROM Device I2C PINS */
#define EEPROM_SCL_PIN              IfxI2c0_SCL_P13_1_INOUT     /* SCL PIN                                          */
#define EEPROM_SDA_PIN              IfxI2c0_SDA_P13_2_INOUT     /* SDA PIN                                          */
#define I2C_BAUDRATE                400000                      /* 400 kHz baud rate                                */

#define EEPROM_DEVICE_ADDRESS       0x50                        /* 7 bit slave device address for reading from EEPROM*/
#define ADDRESS_OF_DATA             0x40                        /* Location of read write, Note: Not a EUI-48 node address (MAC address)    */
#define LENGTH_OF_ADDRESS           1                           /* Length of address of the register, in which the
                                                                   requested MAC address is stored in bytes         */
#define LENGTH_OF_DATA              8                           /* Length of the MAC address in bytes               */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxI2c_I2c g_i2cHandle;                                         /* I2C handle                                       */
IfxI2c_I2c_Device g_i2cDevEeprom;                               /* I2C Slave device handle to EEPROM of MC79411     */

uint8 g_i2cRxBuffer[LENGTH_OF_DATA]                     = {0, 0, 0, 0, 0, 0, 0, 0};    /* Global parameter for 6-byte EUI-48 MAC address   */
uint8 g_i2cTxBuffer[LENGTH_OF_ADDRESS + LENGTH_OF_DATA] = {ADDRESS_OF_DATA, 1, 2, 3, 4, 5, 6, 7, 8};

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


/* This function initializes the I2C in master mode and configures the EEPROM device as an I2C slave */
void init_I2C_module(void)
{
    /* Initialize module */
    IfxI2c_I2c_Config i2cConfig;                                    /* Create configuration structure               */
    IfxI2c_I2c_initConfig(&i2cConfig, &MODULE_I2C0);                /* Fill structure with default values and Module
                                                                       address                                      */
    /* I2c pin configuration */
    const IfxI2c_Pins EEPROM_PINS =
    {
        &EEPROM_SCL_PIN,                                            /* SCL port pin                                 */
        &EEPROM_SDA_PIN,                                            /* SDA port pin                                 */
        IfxPort_PadDriver_ttlSpeed1                                 /* Pad driver mode                              */
    };
    i2cConfig.pins = &EEPROM_PINS;                                  /* Configure port pins                          */
    i2cConfig.baudrate = I2C_BAUDRATE;                              /* Configure baud rate with 400kHz              */

    IfxI2c_I2c_initModule(&g_i2cHandle, &i2cConfig);                /* Initialize module                            */

    /* Initialize device */
    IfxI2c_I2c_deviceConfig i2cDeviceConfig;                        /* Create device configuration                  */
    IfxI2c_I2c_initDeviceConfig(&i2cDeviceConfig, &g_i2cHandle);    /* Fill structure with default values and I2C
                                                                       Handler                                      */
    /* Because it is 7 bit long and bit 0 is R/W bit, the device address has to be shifted by 1 */
    i2cDeviceConfig.deviceAddress = EEPROM_DEVICE_ADDRESS << 1;
    IfxI2c_I2c_initDevice(&g_i2cDevEeprom, &i2cDeviceConfig);       /* Initialize the I2C device handle             */

}

/* This function executes the I2C data transfer.
 * The location of the MAC address is transmitted, then the MAC address is received.
 */
boolean I2C_EEPROM_Test(void)
{
    int i;
    int errorCount = 0;

    /* Communication via I2C starts by transmitting the address of the specific I2C slave until the slave
     * is ready and confirms the reception via the acknowledge bit (IfxI2c_I2c_Status_nak = not acknowledge).
     * This procedure is done for both the write and read process.
     */
    /* Write data to device */
    while(IfxI2c_I2c_write(&g_i2cDevEeprom, &g_i2cTxBuffer[0], sizeof(g_i2cTxBuffer)) == IfxI2c_I2c_Status_nak);
    /* Write data to device to point back to read address*/
    while(IfxI2c_I2c_write(&g_i2cDevEeprom, &g_i2cTxBuffer[0], LENGTH_OF_ADDRESS) == IfxI2c_I2c_Status_nak);
    /* Read the unique MAC address */
    while(IfxI2c_I2c_read(&g_i2cDevEeprom, &g_i2cRxBuffer[0], sizeof(g_i2cRxBuffer)) == IfxI2c_I2c_Status_nak);

    for(i = 0; i < LENGTH_OF_DATA; i++)
    {
        if(g_i2cTxBuffer[i + 1] != g_i2cRxBuffer[i])
        {
            errorCount++;
        }
    }

    if(errorCount == 0)
    {
        waitTime(IfxStm_getTicksFromMilliseconds(600));                       /* Wait 500 milliseconds            */
        return TRUE;
    }
    else
        return FALSE;
}
