/**********************************************************************************************************************
 * \file TMADC_Single_Channel.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAdc_Tmadc.h"
#include "Potentiometer.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define LIMIT_HIGH      0xAAA                                /* Higher limit to be compared with the measure         */
#define LIMIT_LOW       0x555                                /* Lower limit to be compared with the measure          */

#define ADC_MODULE      IfxAdc_TmadcModule_0
#define ADC_CHANNEL     IfxAdc_TmadcChannel_0

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxAdc_Tmadc g_tmadc_pot;                                        /* TMADC module handle                                  */
IfxAdc_Tmadc_Ch g_tmadcChannel_pot;                              /* TMADC channel handle                                 */
IfxAdc_Tmadc_Config g_tmadcConfig_pot;                           /* TMADC configuration structure                        */
IfxAdc_Tmadc_ChConfig g_tmadcChannel0Config_pot;                 /* TMADC channel configuration structure                */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Function to initialize and run the TMADC */
void initTMADC_pot(void)
{
    /* Initialize the TMADC module */
    initTMADCModule_pot();

    /* Initialize the channel */
    initTMADCChannel_pot();

    /* Run the TMADC module */
    IfxAdc_Tmadc_runModule(&g_tmadc_pot);
}

/* Function to initialize the TMADC module */
void initTMADCModule_pot(void)
{
    /* Enable ADC module */
    IfxAdc_enableModule(&MODULE_ADC);

    /* Initialize module to default */
    IfxAdc_Tmadc_initModuleConfig(&g_tmadcConfig_pot, &MODULE_ADC);

    /* Change TMADC configuration */
    g_tmadcConfig_pot.id                = ADC_MODULE;                       /* Module ID                                 */
    g_tmadcConfig_pot.calEnable         = 1;                                /* Calibration enabled                       */

    /* Initialize TMADC module with updated configuration */
    IfxAdc_Tmadc_initModule(&g_tmadc_pot, &g_tmadcConfig_pot);
}

/* Function to initialize the TMADC channel */
void initTMADCChannel_pot(void)
{
    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&g_tmadcChannel0Config_pot, &MODULE_ADC);

    /* Change TMADC channel configuration */
    /* Select the channel ID and the respective result register */
    g_tmadcChannel0Config_pot.id             = ADC_CHANNEL;                    /* Channel ID                             */
    g_tmadcChannel0Config_pot.moduleId       = ADC_MODULE;                     /* Select TMADC module                    */
    g_tmadcChannel0Config_pot.samplingTimeNS = 100;                            /* Set sampling time period               */
    g_tmadcChannel0Config_pot.mode           = IfxAdc_TmadcOpMode_continuous;  /* Select operating mode - continuous     */
    g_tmadcChannel0Config_pot.core           = IfxAdc_TmadcSarCore_0;          /* Select TMADC SAR core                  */

    g_tmadcChannel0Config_pot.resultCfg.resultReg   = IfxAdc_TmadcResultReg_0; /* Configure result register              */
    g_tmadcChannel0Config_pot.resultCfg.waitForRead = 1;                       /* Enable wait-for-read mode              */

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel_pot, &g_tmadcChannel0Config_pot);

#ifdef ADC_PORT_PIN
    IfxPort_setPinMode(ADC_PORT_PIN, IfxPort_Mode_inputNoPullDevice);
#endif

}

/* This function retrieves the conversion value and indicates it using LEDs */
boolean Potentiometer_Test(void)
{
    static boolean low_level_flag = FALSE, high_level_flag = FALSE;
    volatile uint16  g_result;


    /* Read result value */
    g_result = IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel_pot);

    if(g_result < LIMIT_LOW)       /* LED1 lights up if the conversion value is smaller than 0x555                   */
    {
        low_level_flag = TRUE;
    }
    else if(g_result > LIMIT_HIGH) /* LED2 lights up if the conversion value is greater than 0xAAA                   */
    {
        high_level_flag = TRUE;
    }


    if((low_level_flag == TRUE) && (high_level_flag == TRUE))
    {
        low_level_flag = high_level_flag = FALSE;
        return TRUE;
    }

    else
        return FALSE;
}
