/**
 * \file  rtl8226b.h
 * \brief
 *
 * \version ASDK_0_6_0
 * \copyright Copyright (c) 2019-2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 */

#ifndef RTL8201F_H
#define RTL8201F_H

/*******************************************************************************
 * HEADER FILES
 *******************************************************************************/
#include "eth_phy.h"

/*******************************************************************************
 * MACROS
 *******************************************************************************/

/*******************************************************************************
 * ENUMS
 *******************************************************************************/


/*******************************************************************************
 * API PROTOTYPES
 *******************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

 /**
  *
  */
 sint32 RTL8201F_Reset(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_IsResetDone(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_IsPhyIdValid(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_Init(ETH_PHY_t *const handle, uint32 config);

 /**
  *
  */
 sint32 RTL8201F_GetInterruptStatus(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_GetLinkStatus(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_GetLinkSpeed(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_GetLinkMode(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_ConfigureLeds(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_DumpRegisters(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_IsAutonegotiationEnabled(ETH_PHY_t *const handle);

 sint32 RTL8201F_RestartAutonegotiation(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_IsAutonegotiationDone(ETH_PHY_t *const handle);

 /**
  *
  */
 sint32 RTL8201F_IsRemoteReceiverOk(ETH_PHY_t *const handle);

sint32 Rtl8201f_EthLinkUp(ETH_PHY_t *const phyInstance_p, uint16 * const speed_p);
sint32 Rtl8201F_Init(ETH_PHY_t *const phyInstance_p);

#ifdef __cplusplus
}
#endif

#endif

