/**
 * \file eth_phy.c
 * \brief Functions to interface to the on-board ethernet phys
 *
 * \version see header file
 * \copyright Copyright (c) 2019-2020 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include <stddef.h>

#include "mii.h"
#include "eth_phy.h"
#include "types.h"

// software reset the PHY via BMCR_RESET bit
sint32 ETH_PHY_Reset(ETH_PHY_t *const handle)
{
  uint16 regval;

  /* Reset PHY*/
  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  regval |= BMCR_RESET;
  if (handle->ethPhyFunc.mdio_write(handle->phyAddr_u8, MII_BMCR, regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;    
  }

  return ETH_PHY_STATUS_OK;
}
  
sint32 ETH_PHY_IsResetDone(ETH_PHY_t *const handle)
{
  uint16 regval;

  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;    
  }
  
  return (((regval & BMCR_RESET) == 0) ? TRUE : FALSE);
}

sint32 ETH_PHY_Suspend(ETH_PHY_t *const handle)
{
  uint16 regval;

  /* Reset PHY*/
  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  regval |= BMCR_PDOWN;
  if (handle->ethPhyFunc.mdio_write(handle->phyAddr_u8, MII_BMCR, regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;    
  }

  return ETH_PHY_STATUS_OK;
}

sint32 ETH_PHY_Resume(ETH_PHY_t *const handle)
{
  uint16 regval;

  /* Reset PHY*/
  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  regval &= ~BMCR_PDOWN;
  if (handle->ethPhyFunc.mdio_write(handle->phyAddr_u8, MII_BMCR, regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;    
  }

  return ETH_PHY_STATUS_OK;
}

sint32 ETH_PHY_GetPhyId(ETH_PHY_t *const handle, uint32 phy_id, uint32 phy_id_msk)
{
  uint16 phy_id1;
  uint16 phy_id2;

  /* Check Device Identification. */
  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_PHYSID1, &phy_id1) != 0)
  {
    return ETH_PHY_STATUS_ERROR;        
  }

  if (handle->ethPhyFunc.mdio_read(handle->phyAddr_u8, MII_PHYSID2, &phy_id2) != 0)
  {
    return ETH_PHY_STATUS_ERROR;        
  }

  if ((((phy_id1 << 16) | phy_id2) & phy_id_msk) != phy_id)
  {
    return FALSE;
  }

  return TRUE;
}

sint32 ETH_PHY_IsAutonegotiationEnabled(ETH_PHY_t *const handle)
{
  uint16 regval;
  uint8 phyAddr_u8 = handle->phyAddr_u8;

  if (handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;            
  }
  
  return (((regval & BMCR_ANENABLE) != 0) ? TRUE : FALSE);
}

sint32 ETH_PHY_IsAutonegotiationDone(ETH_PHY_t *const handle)
{
  uint16 regval;
  uint8 phyAddr_u8 = handle->phyAddr_u8;

  if (handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_BMSR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;            
  }
  
  return (((regval & BMSR_ANEGCOMPLETE) != 0) ? TRUE : FALSE);
}

sint32 ETH_PHY_RestartAutonegotiation(ETH_PHY_t *const handle)
{
  uint16 regval;
  uint8 phyAddr_u8 = handle->phyAddr_u8;

  if (handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  regval |= BMCR_ANRESTART;

  if (handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_BMCR, regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  if (handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_BMCR, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  return TRUE;
}

sint32 ETH_PHY_IsRemoteReceiverOk(ETH_PHY_t *const handle)
{
  uint16 regval;
  uint8 phyAddr_u8 = handle->phyAddr_u8;

  if (handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_STAT1000, &regval) != 0)
  {
    return ETH_PHY_STATUS_ERROR;                
  }

  return (((regval & (LPA_1000MSFAIL | LPA_1000REMRXOK | LPA_1000LOCALRXOK)) == (LPA_1000REMRXOK | LPA_1000LOCALRXOK)) ? TRUE : FALSE);
}

sint32 ETH_PHY_WriteMmdIndirect(ETH_PHY_t *const handle, uint8 dev_addr, uint16 mmd_addr, uint16 data)
{
  uint8 phyAddr_u8;

  if (handle == NULL)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  phyAddr_u8 = handle->phyAddr_u8;
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_CTRL, (dev_addr & MII_MMD_CTRL_DEVAD_MASK) | MII_MMD_CTRL_ADDR);
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_DATA, mmd_addr);
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_CTRL, (dev_addr & MII_MMD_CTRL_DEVAD_MASK) | MII_MMD_CTRL_NOINCR);
  return handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_DATA, data);
}

sint32 ETH_PHY_ReadMmdIndirect(ETH_PHY_t *const handle, uint8 dev_addr, uint16 mmd_addr, uint16 *const data)
{
  uint8 phyAddr_u8;

  if (handle == NULL)
  {
    return ETH_PHY_STATUS_ERROR;
  }

  phyAddr_u8 = handle->phyAddr_u8;
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_CTRL, (dev_addr & MII_MMD_CTRL_DEVAD_MASK) | MII_MMD_CTRL_ADDR);
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_DATA, mmd_addr);
  handle->ethPhyFunc.mdio_write(phyAddr_u8, MII_MMD_CTRL, (dev_addr & MII_MMD_CTRL_DEVAD_MASK) | MII_MMD_CTRL_NOINCR);
  return handle->ethPhyFunc.mdio_read(phyAddr_u8, MII_MMD_DATA, data);
}

sint32 ETH_PHY_ClearEeeAdv(ETH_PHY_t *const handle)
{
  return ETH_PHY_WriteMmdIndirect(handle, MDIO_MMD_AN, MDIO_AN_EEE_ADV, 0);
}

sint32 Eth_deassertPhyReset(ETH_PHY_t *const phyInstance_p)
{
    if (phyInstance_p == NULL)
    {
        return FAILURE;
    }

    if (phyInstance_p->mdioType == ETH_TYPE_GETH)
    {
        if (phyInstance_p->gethPhyIo.MDIO.reset == NULL)
        {
            return SUCCESS;
        }

        IfxPort_setPinHigh(phyInstance_p->gethPhyIo.MDIO.reset->port, phyInstance_p->gethPhyIo.MDIO.reset->pinIndex);
        IfxPort_setPinModeOutput(phyInstance_p->gethPhyIo.MDIO.reset->port, phyInstance_p->gethPhyIo.MDIO.reset->pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    }
    else
    {
        if (phyInstance_p->lethPhyIo.MDIO.reset == NULL)
        {
            return SUCCESS;
        }

        IfxPort_setPinHigh(phyInstance_p->lethPhyIo.MDIO.reset->port, phyInstance_p->lethPhyIo.MDIO.reset->pinIndex);
        IfxPort_setPinModeOutput(phyInstance_p->lethPhyIo.MDIO.reset->port, phyInstance_p->lethPhyIo.MDIO.reset->pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    }
    return SUCCESS;
}

sint32 Eth_assertPhyReset(ETH_PHY_t *const phyInstance_p)
{
    if (phyInstance_p == NULL)
    {
        return FAILURE;
    }

    if (phyInstance_p->mdioType == ETH_TYPE_GETH)
    {
        if  (phyInstance_p->gethPhyIo.MDIO.reset == NULL)
        {
            return SUCCESS;
        }

        IfxPort_setPinLow(phyInstance_p->gethPhyIo.MDIO.reset->port, phyInstance_p->gethPhyIo.MDIO.reset->pinIndex);
        IfxPort_setPinModeOutput(phyInstance_p->gethPhyIo.MDIO.reset->port, phyInstance_p->gethPhyIo.MDIO.reset->pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    }
    else
    {
        if  (phyInstance_p->lethPhyIo.MDIO.reset == NULL)
        {
            return SUCCESS;
        }

        IfxPort_setPinLow(phyInstance_p->lethPhyIo.MDIO.reset->port, phyInstance_p->lethPhyIo.MDIO.reset->pinIndex);
        IfxPort_setPinModeOutput(phyInstance_p->lethPhyIo.MDIO.reset->port, phyInstance_p->lethPhyIo.MDIO.reset->pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    }

    return SUCCESS;
}

sint32 Eth_defaultPhyInit(ETH_PHY_t *const phyInstance_p)
{
    return SUCCESS;
}

sint32 Eth_defaultPhyLinkUp(ETH_PHY_t *const phyInstance_p, uint16 * const speed_u16)
{
    if (phyInstance_p->ethType == ETH_TYPE_GETH)
    {
        *speed_u16 = ETH_PHY_LINK_SPEED_1000M;
    }

    if (phyInstance_p->ethType == ETH_TYPE_LETH)
    {
        if (phyInstance_p->lethPhyIo.ethPhyInterface == ETH_PHY_INTERFACE_TC14)
        {
            *speed_u16 = ETH_PHY_LINK_SPEED_10M;
        }
        else
        {
            *speed_u16 = ETH_PHY_LINK_SPEED_100M;
        }
    }

    return SUCCESS;
}
