/**
 * \file  rtl8226b.c
 * \brief
 *
 * \version ASDK_0_6_0
 * \copyright Copyright (c) 2019-2021 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 */

/*******************************************************************************
* HEADER FILES
*******************************************************************************/
#include <stdio.h>
#include <stddef.h>

#include "types.h"
#include "rtl8201f.h"
#include "mii.h"

/*******************************************************************************
 * API IMPLEMENTATION
 *******************************************************************************/
/*******************************************************************************
 * MACROS
 *******************************************************************************/

/* RTL8201F PHY Status Register */
#define RTL8201F_PHY_STATUS          0x1
#define RTL8201F_PHY_STATUS_SPEED    0x2000
#define RTL8201F_PHY_STATUS_100      0x2000
#define RTL8201F_PHY_STATUS_10       0x0000
#define RTL8201F_PHY_STATUS_DUPLEX   0x0100
#define RTL8201F_PHY_STATUS_LINK     0x0004

#define RTL8201F_PAGE_SELECT         0x1f

#define RTL8201F_TX_DELAY_EN         0x0100
#define RTL8201F_RX_DELAY_EN         0x0004

#define RTL8201F_PHY_LEDCTRL_LED0_LINK10   0x0001
#define RTL8201F_PHY_LEDCTRL_LED0_LINK100  0x0002
#define RTL8201F_PHY_LEDCTRL_LED0_ACT      0x0008
#define RTL8201F_PHY_LEDCTRL_LED1_LINK10   0x0010
#define RTL8201F_PHY_LEDCTRL_LED1_LINK100  0x0020
#define RTL8201F_PHY_LEDCTRL_LED1_ACT      0x0080
#define RTL8201F_PHY_LEDCTRL_LED2_LINK10   0x0100
#define RTL8201F_PHY_LEDCTRL_LED2_LINK100  0x0200
#define RTL8201F_PHY_LEDCTRL_LED2_ACT      0x0800

#define RTL8201F_PHY_ID                    0x001CC810      /* PHY_ID for RTL8201f */
#define RTL8201F_PHY_ID_MSK                0xFFFFFFF0      /* PHY_ID for RTL8201f */

/*******************************************************************************
 * API IMPLEMENTATION
 *******************************************************************************/
sint32 RTL8201F_Reset(ETH_PHY_t *const handle)
{
    return ETH_PHY_Reset(handle);
}

sint32 RTL8201F_IsResetDone(ETH_PHY_t *const handle)
{
    return ETH_PHY_IsResetDone(handle);
}

sint32 RTL8201F_IsPhyIdValid(ETH_PHY_t *const handle)
{
    return ETH_PHY_GetPhyId(handle, RTL8201F_PHY_ID, RTL8201F_PHY_ID_MSK);
}

sint32 RTL8201F_Phy_Init(ETH_PHY_t *const handle, uint32 config)
{
    (void)config;
    uint32 retries;
    uint16 regval;
    uint8 phy_addr;
    uint16 bmcr;
    uint16 bmsr;

    if (handle == NULL)
    {
        return ETH_PHY_STATUS_ERROR;
    }

    phy_addr = handle->phyAddr_u8;
    RTL8201F_Reset(handle);

    retries = 0xffff;
    while ((RTL8201F_IsPhyIdValid(handle) != TRUE) && --retries);
    if (retries == 0)
    {
        return ETH_PHY_STATUS_ERROR_ID;
    }

    /* restore to default page 0 */
    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x7);
    handle->ethPhyFunc.mdio_read(phy_addr, 16, &regval); /* RMSR */
    regval |= 1 << 2; /* 0 = CSR/CSR_DV pin = CSR_DV signal, 1 = CSR/CSR_DV pin = RXDV signal */
    regval |= 1 << 3; /* 0 = MII Mode, 1 = RMII Mode */
    handle->ethPhyFunc.mdio_write(phy_addr, 16, regval);
    handle->ethPhyFunc.mdio_read(phy_addr, 16, &regval); /* RMSR */

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);
    handle->ethPhyFunc.mdio_read(phy_addr, MII_BMCR, &bmcr);
    bmcr |= 1 << 9; /* restart auto neg.  */
    handle->ethPhyFunc.mdio_write(phy_addr, MII_BMCR, bmcr);
    do
    {
        handle->ethPhyFunc.mdio_read(phy_addr, MII_BMSR, &bmsr);
    }
    while ((bmsr & (1 << 5)) == 0);

    return ETH_PHY_STATUS_OK;
}

sint32 RTL8201F_GetLinkStatus(ETH_PHY_t *const handle)
{
    uint16 regval;
    uint8 phy_addr = handle->phyAddr_u8;

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);
    handle->ethPhyFunc.mdio_read(phy_addr, MII_BMSR, &regval);
    handle->ethPhyFunc.mdio_read(phy_addr, MII_BMSR, &regval);

    return ((regval & RTL8201F_PHY_STATUS_LINK) ? ETH_PHY_LINK_STATUS_UP : ETH_PHY_LINK_STATUS_DOWN);
}

sint32 RTL8201F_GetLinkSpeed(ETH_PHY_t *const handle)
{
    uint16 regval;
    sint32 res;

    uint8 phy_addr = handle->phyAddr_u8;

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);
    handle->ethPhyFunc.mdio_read(phy_addr, MII_BMCR, &regval);

    regval = (regval & RTL8201F_PHY_STATUS_SPEED);

    switch (regval)
    {
    case RTL8201F_PHY_STATUS_100:
        res = ETH_PHY_LINK_SPEED_100M;
        break;
    default:
        res = ETH_PHY_LINK_SPEED_10M;
    }
    return (res);
}

/* Get link duplex settings */
sint32 RTL8201F_GetLinkMode(ETH_PHY_t *const handle)
{
    uint16 regval;
    uint8 phy_addr = handle->phyAddr_u8;

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);
    handle->ethPhyFunc.mdio_read(phy_addr, MII_BMCR, &regval);

    return ((regval & RTL8201F_PHY_STATUS_DUPLEX) ? ETH_PHY_LINK_DUPLEX_FULL : ETH_PHY_LINK_DUPLEX_HALF);
}

sint32 RTL8201F_GetInterruptStatus(ETH_PHY_t *const handle)
{

    return 0;
}

sint32 RTL8201F_ConfigureLeds(ETH_PHY_t *const handle)
{
    uint16 regval;
    uint8 phy_addr = handle->phyAddr_u8;

    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x7);
    handle->ethPhyFunc.mdio_read(phy_addr, 19, &regval);
    regval |= (1 << 3); /* 0 = customized led disabled, 1 = customized led enabled */
    handle->ethPhyFunc.mdio_write(phy_addr, 19, regval);

    handle->ethPhyFunc.mdio_write(phy_addr, 0x11, RTL8201F_PHY_LEDCTRL_LED0_LINK10 | RTL8201F_PHY_LEDCTRL_LED0_ACT |
                                  RTL8201F_PHY_LEDCTRL_LED1_LINK100 | RTL8201F_PHY_LEDCTRL_LED1_ACT);
    /* restore to default page 0 */
    handle->ethPhyFunc.mdio_write(phy_addr, RTL8201F_PAGE_SELECT, 0x0);

    return 0;
}

sint32 RTL8201F_IsAutonegotiationEnabled(ETH_PHY_t *const handle)
{
    return ETH_PHY_IsAutonegotiationEnabled(handle);
}

sint32 RTL8201F_IsAutonegotiationDone(ETH_PHY_t *const handle)
{
    return ETH_PHY_IsAutonegotiationDone(handle);
}

sint32 RTL8201F_RestartAutonegotiation(ETH_PHY_t *const handle)
{
    return ETH_PHY_RestartAutonegotiation(handle);
}


sint32 RTL8201F_IsRemoteReceiverOk(ETH_PHY_t *const handle)
{
    return ETH_PHY_IsRemoteReceiverOk(handle);
}

sint32 Rtl8201F_Init(ETH_PHY_t *const phyInstance_p)
{
    sint32 result_s32;
    result_s32 = FAILURE;

    if (phyInstance_p == NULL)
    {
        return FAILURE;
    }

    /*********************************************************************************************************************************************/
    /* Realtek: init Phy                                                                                                                         */
    /*********************************************************************************************************************************************/
    if (RTL8201F_Phy_Init(phyInstance_p, (uint32)(ETH_PHY_CONFIG_INTERFACE_RMII | ETH_PHY_CONFIG_AUTONEG | ETH_PHY_CONFIG_ENABLE_CLKOUT)) == SUCCESS)
    {
        printf("Phy%i: RTL8201F_Init() = SUCCESS"EOL, phyInstance_p->hsphyPort_u8);
    }
    else
    {
        printf("Phy%i: RTL8201F_Init() = FAIL"EOL, phyInstance_p->hsphyPort_u8);
        return FAILURE;
    }

    return SUCCESS;
}

sint32 Rtl8201f_EthLinkUp(ETH_PHY_t *const phyInstance_p, uint16 * const speed_p)
{
    sint32 result_s32;
    uint32 timeout_u32;
    boolean linkActive_b;

    result_s32 = FAILURE;

    if (phyInstance_p == NULL)
    {
        return FAILURE;
    }

    /*********************************************************************************************************************************************/
    /* Realtek: wait for AutoNegotiation                                                                                                        */
    /*********************************************************************************************************************************************/
    if (RTL8201F_IsAutonegotiationEnabled(phyInstance_p))
    {
        while (RTL8201F_IsAutonegotiationDone(phyInstance_p) == FALSE);
    }

    /*********************************************************************************************************************************************/
    /* Realtek: check ethernet link state                                                                                                        */
    /*********************************************************************************************************************************************/

    printf("Phy%i: wait for Rtl8201F_is_link()"EOL, phyInstance_p->macPort_u8);
    timeout_u32 = 0xFFFF;
    do
    {
        result_s32 = RTL8201F_GetLinkStatus(phyInstance_p);
        timeout_u32--;
    }
    while ((result_s32 != ETH_PHY_LINK_STATUS_UP) && (timeout_u32 > 0));

    if ((timeout_u32 == 0) || (result_s32 != ETH_PHY_LINK_STATUS_UP))
    {
        return FAILURE;
    }

    linkActive_b = TRUE;
    /*********************************************************************************************************************************************/
    /* Realtek: get ethernet link speed                                                                                                          */
    /*********************************************************************************************************************************************/
    *speed_p = (uint16)RTL8201F_GetLinkSpeed(phyInstance_p);


    if (linkActive_b == TRUE)
    {
        printf("Phy%i: Eth Link up, Speed = %i"EOL, phyInstance_p->macPort_u8, (int)*speed_p);
    }
    else
    {
        printf("Phy%i: Eth Link down, Speed = %i"EOL, phyInstance_p->macPort_u8, (int)*speed_p);
        return FAILURE;
    }

    return SUCCESS;
}
