/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_GETH_PROT_CFG_H
#define TC4D_GETH_PROT_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define GETH_ACCENCH0_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH0_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH0_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH0_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH1_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH1_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH1_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH1_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH2_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH2_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH2_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH2_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH3_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH3_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH3_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH3_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH4_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH4_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH4_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH4_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH5_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH5_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH5_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH5_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH6_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH6_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH6_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH6_WRB (0x0) /*decimal 0*/

#define GETH_ACCENCH7_RDA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH7_RDB (0x0) /*decimal 0*/

#define GETH_ACCENCH7_WRA (0x10000003) /*decimal 268435459*/

#define GETH_ACCENCH7_WRB (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH0_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH0_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH0_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH0_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH0_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH0_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH1_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH1_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH2_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH2_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH3_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH3_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH4_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH4_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH5_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH5_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH6_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH6_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_DMA_ACCENCH7_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_DMA_ACCENCH7_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ0_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ1_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ2_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ3_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ4_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ5_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ6_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC0_TCQ7_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ0_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ1_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ2_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ3_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ4_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ5_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ6_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define GETH_MAC1_TCQ7_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#define LED_ACCEN_RDA_EN00 (0x1) /*decimal 1*/

#define LED_ACCEN_RDA_EN01 (0x1) /*decimal 1*/

#define LED_ACCEN_RDA_EN02 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN03 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN04 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN05 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN06 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN07 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN08 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN09 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN10 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN11 (0x0) /*decimal 0*/

#define LED_ACCEN_RDA_EN28 (0x1) /*decimal 1*/

#define LED_ACCEN_WRA_EN00 (0x1) /*decimal 1*/

#define LED_ACCEN_WRA_EN01 (0x1) /*decimal 1*/

#define LED_ACCEN_WRA_EN02 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN03 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN04 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN05 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN06 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN07 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN08 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN09 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN10 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN11 (0x0) /*decimal 0*/

#define LED_ACCEN_WRA_EN28 (0x1) /*decimal 1*/

#endif /* TC4D_GETH_PROT_CFG_H */
