/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_GETH_MAC_CFG_H
#define TC4D_GETH_MAC_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define GETH_MACEN (0x1) /*decimal 1*/

#define GETH_PORT0_CBS_BITS_PER_CLK (8.00000)

#define GETH_PORT0_CBS_CLK_PERIOD_NS (8.00000)

#define GETH_PORT0_MAC_ADDRESS0 00:03:19:00:00:00

#define GETH_PORT0_MAC_ADDRESS0_HIGH (0x80000000) /*decimal 2147483648*/

#define GETH_PORT0_MAC_ADDRESS0_LOW (0x190300) /*decimal 1639168*/

#define GETH_PORT0_MAC_ADDRESS0_SA (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_ADDRESS1 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS1_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS1_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS2 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS2_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS2_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS3 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS3_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS3_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS4 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS4_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS4_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS5 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS5_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS5_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS6 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS6_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS6_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS7 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS7_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS7_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS8 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS8_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS8_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_ADDRESS9 FF:FF:FF:FF:FF:FF

#define GETH_PORT0_MAC_ADDRESS9_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT0_MAC_ADDRESS9_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT0_MAC_DCHSEL_INDREG0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG8 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DCHSEL_INDREG9 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG0 (0x1) /*decimal 1*/

#define GETH_PORT0_MAC_DPCSEL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG8 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_DPCSEL_INDREG9 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_EXTENDED_CONFIGURATION (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_FILTER_Cont_Calc (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_FPCSEL_INDREG0 (0x100) /*decimal 256*/

#define GETH_PORT0_MAC_FPE_CTRL_STS (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_GRAPH_COLOR ABD9E4

#define GETH_PORT0_MAC_INNER_VLAN_INCL (0x40000) /*decimal 262144*/

#define GETH_PORT0_MAC_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_RXESIS_ISR enter callback function here

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_TGTTIMEREACHED (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_TGTTIMEREACHED_ISR enter callback function here

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_TSCAPTURED (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_TSCAPTURED_ISR enter callback function here

#define GETH_PORT0_MAC_INTERRUPT_ENABLE_TXESIS_ISR enter callback function here

#define GETH_PORT0_MAC_PACKET_FILTER (0x800000011) /*decimal 2147549201*/

#define GETH_PORT0_MAC_PCCTRL_INDREG0 (0x9) /*decimal 9*/

#define GETH_PORT0_MAC_PCCTRL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCCTRL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR0 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR1 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR2 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR3 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR4 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR5 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR6 enter callback function here

#define GETH_PORT0_MAC_PCTH_INTR_ENABLE_ISR7 enter callback function here

#define GETH_PORT0_MAC_PPS0_INTERVAL (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS0_INTERVAL_USER (0.00000)

#define GETH_PORT0_MAC_PPS0_PIN IfxGeth0_P0_PPS_P14_3_OUT

#define GETH_PORT0_MAC_PPS0_PIN_SEL (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS0_TARGET_TIME (0.00000)

#define GETH_PORT0_MAC_PPS0_TARGET_TIME_NANOSECONDS (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS0_TARGET_TIME_SECONDS (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS0_WIDTH (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS0_WIDTH_PPSWIDTH (0.00000)

#define GETH_PORT0_MAC_PPS_CONTROL (0x60) /*decimal 96*/

#define GETH_PORT0_MAC_PPS_CONTROL_FIXED_PPSCTRL0_PPSCMD0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_PPS_CONTROL_FLEX_PPSCTRL0_PPSCMD0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL0 (0x2) /*decimal 2*/

#define GETH_PORT0_MAC_RXQ_CTRL1 (0x8010) /*decimal 32784*/

#define GETH_PORT0_MAC_RXQ_CTRL2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL4_VFFQE_CONT_CALC (0x1) /*decimal 1*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ0_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ1_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ2_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ3_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ4_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ5_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ6_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RXQ_CTRL_PSRQ7_7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_RX_CONFIGURATION (0x88) /*decimal 136*/

#define GETH_PORT0_MAC_Rx0_AvVis hidden

#define GETH_PORT0_MAC_Rx0_DisVis hidden

#define GETH_PORT0_MAC_Rx0_EnVis visible

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx0_Link visible

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx0_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx1_AvVis hidden

#define GETH_PORT0_MAC_Rx1_DisVis visible

#define GETH_PORT0_MAC_Rx1_EnVis hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx1_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx2_AvVis hidden

#define GETH_PORT0_MAC_Rx2_DisVis visible

#define GETH_PORT0_MAC_Rx2_EnVis hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx2_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx3_AvVis hidden

#define GETH_PORT0_MAC_Rx3_DisVis visible

#define GETH_PORT0_MAC_Rx3_EnVis hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx3_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx4_AvVis hidden

#define GETH_PORT0_MAC_Rx4_DisVis visible

#define GETH_PORT0_MAC_Rx4_EnVis hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx4_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx5_AvVis hidden

#define GETH_PORT0_MAC_Rx5_DisVis visible

#define GETH_PORT0_MAC_Rx5_EnVis hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx5_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx6_AvVis hidden

#define GETH_PORT0_MAC_Rx6_DisVis visible

#define GETH_PORT0_MAC_Rx6_EnVis hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx6_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_Rx7_AvVis hidden

#define GETH_PORT0_MAC_Rx7_DisVis visible

#define GETH_PORT0_MAC_Rx7_EnVis hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx0_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx1_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx2_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx3_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx4_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx5_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx6_Link hidden

#define GETH_PORT0_MAC_Rx7_To_Brdg_Rx7_Link hidden

#define GETH_PORT0_MAC_TIMESTAMP_CONTROL (0x300) /*decimal 768*/

#define GETH_PORT0_MAC_TIMESTAMP_FPTP (0xBEBC200) /*decimal 200000000*/

#define GETH_PORT0_MAC_TX_CONFIGURATION (0x60000000) /*decimal 1610612736*/

#define GETH_PORT0_MAC_To_Brdg_Rx0_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx1_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx2_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx3_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx4_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx5_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx6_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Rx7_EnVis hidden

#define GETH_PORT0_MAC_To_Brdg_Tx0_Link visible

#define GETH_PORT0_MAC_To_Brdg_Tx1_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx2_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx3_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx4_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx5_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx6_Link hidden

#define GETH_PORT0_MAC_To_Brdg_Tx7_Link hidden

#define GETH_PORT0_MAC_Tx0_AvVis hidden

#define GETH_PORT0_MAC_Tx0_DisVis hidden

#define GETH_PORT0_MAC_Tx0_EnVis visible

#define GETH_PORT0_MAC_Tx1_AvVis hidden

#define GETH_PORT0_MAC_Tx1_DisVis visible

#define GETH_PORT0_MAC_Tx1_EnVis hidden

#define GETH_PORT0_MAC_Tx2_AvVis hidden

#define GETH_PORT0_MAC_Tx2_DisVis visible

#define GETH_PORT0_MAC_Tx2_EnVis hidden

#define GETH_PORT0_MAC_Tx3_AvVis hidden

#define GETH_PORT0_MAC_Tx3_DisVis visible

#define GETH_PORT0_MAC_Tx3_EnVis hidden

#define GETH_PORT0_MAC_Tx4_AvVis hidden

#define GETH_PORT0_MAC_Tx4_DisVis visible

#define GETH_PORT0_MAC_Tx4_EnVis hidden

#define GETH_PORT0_MAC_Tx5_AvVis hidden

#define GETH_PORT0_MAC_Tx5_DisVis visible

#define GETH_PORT0_MAC_Tx5_EnVis hidden

#define GETH_PORT0_MAC_Tx6_AvVis hidden

#define GETH_PORT0_MAC_Tx6_DisVis visible

#define GETH_PORT0_MAC_Tx6_EnVis hidden

#define GETH_PORT0_MAC_Tx7_AvVis hidden

#define GETH_PORT0_MAC_Tx7_DisVis visible

#define GETH_PORT0_MAC_Tx7_EnVis hidden

#define GETH_PORT0_MAC_VLAN_INCL (0x140000) /*decimal 1310720*/

#define GETH_PORT0_MAC_VLAN_INCL0 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL1 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL2 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL3 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL4 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL5 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL6 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_INCL7 (0x0) /*decimal 0*/

#define GETH_PORT0_MAC_VLAN_TAG_CTRL (0x1080000) /*decimal 17301504*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER0 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER1 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER2 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER3 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER4 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER5 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER6 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MAC_VLAN_TAG_FILTER7 (0x1000000) /*decimal 16777216*/

#define GETH_PORT0_MTL_ECC_CONTROL (0x2F) /*decimal 47*/

#define GETH_PORT0_MTL_ECC_CONTROL_ALL (0x1) /*decimal 1*/

#define GETH_PORT0_MTL_EST_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_BTR_NSEC (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_BTR_SEC (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_CTR_NSEC (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_DATA0 (0x10003E8) /*decimal 16778216*/

#define GETH_PORT0_MTL_EST_GCL_DATA1 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA2 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA3 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA4 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA5 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA6 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA7 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA8 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_DATA9 (0x3E8) /*decimal 1000*/

#define GETH_PORT0_MTL_EST_GCL_IDX0_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX1_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX2_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX3_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX4_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX5_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX6_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX7_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX8_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_IDX9_EN (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_EST_GCL_LLR (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_FPE_ADVANCE (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_FPE_CTRL_STS (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_OPERATION_MODE (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_QUEUE0_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE1_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE2_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE3_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE4_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE5_BANDWIDTH_RES (30.00000)

#define GETH_PORT0_MTL_QUEUE5_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE5_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT0_MTL_QUEUE5_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE5_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_QUEUE5_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE5_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_QUEUE6_BANDWIDTH_RES (30.00000)

#define GETH_PORT0_MTL_QUEUE6_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE6_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT0_MTL_QUEUE6_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE6_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_QUEUE6_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE6_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_QUEUE7_BANDWIDTH_RES (30.00000)

#define GETH_PORT0_MTL_QUEUE7_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE7_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT0_MTL_QUEUE7_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE7_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_QUEUE7_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT0_MTL_QUEUE7_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT0_MTL_RXQ0_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_RXQ0_OPERATION_MODE (0xF0020) /*decimal 983072*/

#define GETH_PORT0_MTL_RXQ1_CONTROL (0x1) /*decimal 1*/

#define GETH_PORT0_MTL_RXQ1_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ2_CONTROL (0x2) /*decimal 2*/

#define GETH_PORT0_MTL_RXQ2_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ3_CONTROL (0x3) /*decimal 3*/

#define GETH_PORT0_MTL_RXQ3_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ4_CONTROL (0x4) /*decimal 4*/

#define GETH_PORT0_MTL_RXQ4_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ5_CONTROL (0x5) /*decimal 5*/

#define GETH_PORT0_MTL_RXQ5_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ6_CONTROL (0x6) /*decimal 6*/

#define GETH_PORT0_MTL_RXQ6_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ7_CONTROL (0x7) /*decimal 7*/

#define GETH_PORT0_MTL_RXQ7_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT0_MTL_RXQ_DMA_MAP0 (0x3020180) /*decimal 50463104*/

#define GETH_PORT0_MTL_RXQ_DMA_MAP1 (0x7060504) /*decimal 117835012*/

#define GETH_PORT0_MTL_TC0_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC0_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC1_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC1_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC2_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC2_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC3_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC3_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC4_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC4_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC5_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC5_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC5_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC5_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC5_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC5_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC5_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC5_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC5_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC5_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC5_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TC5_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TC6_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC6_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC6_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC6_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC6_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC6_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC6_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC6_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC6_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC6_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC6_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TC6_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TC7_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC7_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC7_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC7_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT0_MTL_TC7_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT0_MTL_TC7_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC7_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC7_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT0_MTL_TC7_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC7_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT0_MTL_TC7_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TC7_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT0_MTL_TXQ0_OPERATION_MODE (0x1F000A) /*decimal 2031626*/

#define GETH_PORT0_MTL_TXQ1_OPERATION_MODE (0x70100) /*decimal 459008*/

#define GETH_PORT0_MTL_TXQ2_OPERATION_MODE (0x70200) /*decimal 459264*/

#define GETH_PORT0_MTL_TXQ3_OPERATION_MODE (0x70300) /*decimal 459520*/

#define GETH_PORT0_MTL_TXQ4_OPERATION_MODE (0x70400) /*decimal 459776*/

#define GETH_PORT0_MTL_TXQ5_OPERATION_MODE (0x70500) /*decimal 460032*/

#define GETH_PORT0_MTL_TXQ6_OPERATION_MODE (0x70600) /*decimal 460288*/

#define GETH_PORT0_MTL_TXQ7_OPERATION_MODE (0x70700) /*decimal 460544*/

#define GETH_PORT0_TRANSMIT_CLK_PERIOD_NS (1.00000)

#define GETH_PORT1_CBS_BITS_PER_CLK (8.00000)

#define GETH_PORT1_CBS_CLK_PERIOD_NS (8.00000)

#define GETH_PORT1_MAC_ADDRESS0 00:03:19:00:01:00

#define GETH_PORT1_MAC_ADDRESS0_HIGH (0x80000001) /*decimal 2147483649*/

#define GETH_PORT1_MAC_ADDRESS0_LOW (0x190300) /*decimal 1639168*/

#define GETH_PORT1_MAC_ADDRESS0_SA (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_ADDRESS1 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS1_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS1_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS2 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS2_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS2_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS3 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS3_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS3_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS4 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS4_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS4_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS5 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS5_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS5_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS6 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS6_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS6_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS7 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS7_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS7_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS8 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS8_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS8_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_ADDRESS9 FF:FF:FF:FF:FF:FF

#define GETH_PORT1_MAC_ADDRESS9_HIGH (0xFFFF) /*decimal 65535*/

#define GETH_PORT1_MAC_ADDRESS9_LOW (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_PORT1_MAC_DCHSEL_INDREG0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG8 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DCHSEL_INDREG9 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG8 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_DPCSEL_INDREG9 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_EXTENDED_CONFIGURATION (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_FILTER_Cont_Calc (0x1) /*decimal 1*/

#define GETH_PORT1_MAC_FPCSEL_INDREG0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_FPE_CTRL_STS (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_GRAPH_COLOR D0D0D0

#define GETH_PORT1_MAC_INNER_VLAN_INCL (0x40000) /*decimal 262144*/

#define GETH_PORT1_MAC_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_INTERRUPT_ENABLE_RXESIS_ISR enter callback function here

#define GETH_PORT1_MAC_INTERRUPT_ENABLE_TSIE_ISR enter callback function here

#define GETH_PORT1_MAC_INTERRUPT_ENABLE_TXESIS_ISR enter callback function here

#define GETH_PORT1_MAC_PACKET_FILTER (0x80010000) /*decimal 2147549184*/

#define GETH_PORT1_MAC_PCCTRL_INDREG0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCCTRL_INDREG7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR0 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR1 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR2 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR3 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR4 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR5 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR6 enter callback function here

#define GETH_PORT1_MAC_PCTH_INTR_ENABLE_ISR7 enter callback function here

#define GETH_PORT1_MAC_PPS0_INTERVAL (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS0_INTERVAL_USER (0.00000)

#define GETH_PORT1_MAC_PPS0_PIN IfxGeth0_P1_PPS_P14_4_OUT

#define GETH_PORT1_MAC_PPS0_PIN_SEL (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS0_TARGET_TIME (0.00000)

#define GETH_PORT1_MAC_PPS0_TARGET_TIME_NANOSECONDS (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS0_TARGET_TIME_SECONDS (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS0_WIDTH (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS0_WIDTH_PPSWIDTH (0.00000)

#define GETH_PORT1_MAC_PPS_CONTROL (0x60) /*decimal 96*/

#define GETH_PORT1_MAC_PPS_CONTROL_FIXED_PPSCTRL0_PPSCMD0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_PPS_CONTROL_FLEX_PPSCTRL0_PPSCMD0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL1 (0x10) /*decimal 16*/

#define GETH_PORT1_MAC_RXQ_CTRL2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL4_VFFQE_CONT_CALC (0x1) /*decimal 1*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ0_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ1_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ2_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ3_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ4_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ5_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ6_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RXQ_CTRL_PSRQ7_7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_RX_CONFIGURATION (0x88) /*decimal 136*/

#define GETH_PORT1_MAC_Rx0_AvVis hidden

#define GETH_PORT1_MAC_Rx0_DisVis visible

#define GETH_PORT1_MAC_Rx0_EnVis hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx0_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx1_AvVis hidden

#define GETH_PORT1_MAC_Rx1_DisVis visible

#define GETH_PORT1_MAC_Rx1_EnVis hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx1_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx2_AvVis hidden

#define GETH_PORT1_MAC_Rx2_DisVis visible

#define GETH_PORT1_MAC_Rx2_EnVis hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx2_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx3_AvVis hidden

#define GETH_PORT1_MAC_Rx3_DisVis visible

#define GETH_PORT1_MAC_Rx3_EnVis hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx3_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx4_AvVis hidden

#define GETH_PORT1_MAC_Rx4_DisVis visible

#define GETH_PORT1_MAC_Rx4_EnVis hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx4_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx5_AvVis hidden

#define GETH_PORT1_MAC_Rx5_DisVis visible

#define GETH_PORT1_MAC_Rx5_EnVis hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx5_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx6_AvVis hidden

#define GETH_PORT1_MAC_Rx6_DisVis visible

#define GETH_PORT1_MAC_Rx6_EnVis hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx6_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_Rx7_AvVis hidden

#define GETH_PORT1_MAC_Rx7_DisVis visible

#define GETH_PORT1_MAC_Rx7_EnVis hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx0_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx1_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx2_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx3_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx4_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx5_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx6_Link hidden

#define GETH_PORT1_MAC_Rx7_To_Brdg_Rx7_Link hidden

#define GETH_PORT1_MAC_TIMESTAMP_CONTROL (0x300) /*decimal 768*/

#define GETH_PORT1_MAC_TIMESTAMP_FPTP (0xBEBC200) /*decimal 200000000*/

#define GETH_PORT1_MAC_TX_CONFIGURATION (0x60000000) /*decimal 1610612736*/

#define GETH_PORT1_MAC_To_Brdg_Rx0_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx1_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx2_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx3_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx4_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx5_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx6_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Rx7_EnVis hidden

#define GETH_PORT1_MAC_To_Brdg_Tx0_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx1_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx2_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx3_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx4_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx5_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx6_Link hidden

#define GETH_PORT1_MAC_To_Brdg_Tx7_Link hidden

#define GETH_PORT1_MAC_Tx0_AvVis hidden

#define GETH_PORT1_MAC_Tx0_DisVis visible

#define GETH_PORT1_MAC_Tx0_EnVis hidden

#define GETH_PORT1_MAC_Tx1_AvVis hidden

#define GETH_PORT1_MAC_Tx1_DisVis visible

#define GETH_PORT1_MAC_Tx1_EnVis hidden

#define GETH_PORT1_MAC_Tx2_AvVis hidden

#define GETH_PORT1_MAC_Tx2_DisVis visible

#define GETH_PORT1_MAC_Tx2_EnVis hidden

#define GETH_PORT1_MAC_Tx3_AvVis hidden

#define GETH_PORT1_MAC_Tx3_DisVis visible

#define GETH_PORT1_MAC_Tx3_EnVis hidden

#define GETH_PORT1_MAC_Tx4_AvVis hidden

#define GETH_PORT1_MAC_Tx4_DisVis visible

#define GETH_PORT1_MAC_Tx4_EnVis hidden

#define GETH_PORT1_MAC_Tx5_AvVis hidden

#define GETH_PORT1_MAC_Tx5_DisVis visible

#define GETH_PORT1_MAC_Tx5_EnVis hidden

#define GETH_PORT1_MAC_Tx6_AvVis hidden

#define GETH_PORT1_MAC_Tx6_DisVis visible

#define GETH_PORT1_MAC_Tx6_EnVis hidden

#define GETH_PORT1_MAC_Tx7_AvVis hidden

#define GETH_PORT1_MAC_Tx7_DisVis visible

#define GETH_PORT1_MAC_Tx7_EnVis hidden

#define GETH_PORT1_MAC_VLAN_INCL (0x140000) /*decimal 1310720*/

#define GETH_PORT1_MAC_VLAN_INCL0 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL1 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL2 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL3 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL4 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL5 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL6 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_INCL7 (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_TAG_CTRL (0x0) /*decimal 0*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER0 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER1 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER2 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER3 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER4 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER5 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER6 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MAC_VLAN_TAG_FILTER7 (0x1000000) /*decimal 16777216*/

#define GETH_PORT1_MTL_ECC_CONTROL (0x2F) /*decimal 47*/

#define GETH_PORT1_MTL_ECC_CONTROL_ALL (0x1) /*decimal 1*/

#define GETH_PORT1_MTL_EST_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_BTR_NSEC (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_BTR_SEC (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_CTR_NSEC (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_DATA0 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA1 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA2 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA3 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA4 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA5 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA6 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA7 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA8 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_DATA9 (0x3E8) /*decimal 1000*/

#define GETH_PORT1_MTL_EST_GCL_IDX0_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX1_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX2_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX3_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX4_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX5_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX6_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX7_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX8_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_IDX9_EN (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_EST_GCL_LLR (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_FPE_ADVANCE (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_FPE_CTRL_STS (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_OPERATION_MODE (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_QUEUE0_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE1_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE2_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE3_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE4_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE5_BANDWIDTH_RES (30.00000)

#define GETH_PORT1_MTL_QUEUE5_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE5_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT1_MTL_QUEUE5_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE5_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_QUEUE5_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE5_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_QUEUE6_BANDWIDTH_RES (30.00000)

#define GETH_PORT1_MTL_QUEUE6_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE6_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT1_MTL_QUEUE6_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE6_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_QUEUE6_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE6_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_QUEUE7_BANDWIDTH_RES (30.00000)

#define GETH_PORT1_MTL_QUEUE7_BE_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE7_CBS_AUTO_CALC (0x1) /*decimal 1*/

#define GETH_PORT1_MTL_QUEUE7_CBS_MAXPAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE7_IDLESLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_QUEUE7_PAYLOAD_SIZE (0x40) /*decimal 64*/

#define GETH_PORT1_MTL_QUEUE7_SENDSLOPE_TICKS (0x5E) /*decimal 94*/

#define GETH_PORT1_MTL_RXQ0_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_RXQ0_OPERATION_MODE (0x70020) /*decimal 458784*/

#define GETH_PORT1_MTL_RXQ1_CONTROL (0x1) /*decimal 1*/

#define GETH_PORT1_MTL_RXQ1_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ2_CONTROL (0x2) /*decimal 2*/

#define GETH_PORT1_MTL_RXQ2_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ3_CONTROL (0x3) /*decimal 3*/

#define GETH_PORT1_MTL_RXQ3_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ4_CONTROL (0x4) /*decimal 4*/

#define GETH_PORT1_MTL_RXQ4_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ5_CONTROL (0x5) /*decimal 5*/

#define GETH_PORT1_MTL_RXQ5_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ6_CONTROL (0x6) /*decimal 6*/

#define GETH_PORT1_MTL_RXQ6_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ7_CONTROL (0x7) /*decimal 7*/

#define GETH_PORT1_MTL_RXQ7_OPERATION_MODE (0x70000) /*decimal 458752*/

#define GETH_PORT1_MTL_RXQ_DMA_MAP0 (0x3020100) /*decimal 50462976*/

#define GETH_PORT1_MTL_RXQ_DMA_MAP1 (0x7060504) /*decimal 117835012*/

#define GETH_PORT1_MTL_TC0_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC0_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC1_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC1_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC2_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC2_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC3_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC3_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC4_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC4_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC5_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC5_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC5_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC5_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC5_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC5_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC5_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC5_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC5_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC5_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC5_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TC5_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TC6_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC6_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC6_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC6_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC6_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC6_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC6_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC6_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC6_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC6_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC6_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TC6_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TC7_CBS_IDLESLOPE (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC7_ETS_CONTROL (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC7_HICREDIT (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC7_HICREDIT_CALC (0x3862E) /*decimal 230958*/

#define GETH_PORT1_MTL_TC7_IDLESLOPE_CALC (0x999) /*decimal 2457*/

#define GETH_PORT1_MTL_TC7_LOCREDIT (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC7_LOCREDIT_CALC (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC7_LOCREDIT_CALC2 (0x1FF7C68C) /*decimal 536331916*/

#define GETH_PORT1_MTL_TC7_QUANTUM_WEIGHT (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC7_QUANTUM_WEIGHT_QW (0x0) /*decimal 0*/

#define GETH_PORT1_MTL_TC7_SENDSLOPECREDIT (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TC7_SENDSLOPE_CALC (0x1666) /*decimal 5734*/

#define GETH_PORT1_MTL_TXQ0_OPERATION_MODE (0x70002) /*decimal 458754*/

#define GETH_PORT1_MTL_TXQ1_OPERATION_MODE (0x70100) /*decimal 459008*/

#define GETH_PORT1_MTL_TXQ2_OPERATION_MODE (0x70200) /*decimal 459264*/

#define GETH_PORT1_MTL_TXQ3_OPERATION_MODE (0x70300) /*decimal 459520*/

#define GETH_PORT1_MTL_TXQ4_OPERATION_MODE (0x70400) /*decimal 459776*/

#define GETH_PORT1_MTL_TXQ5_OPERATION_MODE (0x70500) /*decimal 460032*/

#define GETH_PORT1_MTL_TXQ6_OPERATION_MODE (0x70600) /*decimal 460288*/

#define GETH_PORT1_MTL_TXQ7_OPERATION_MODE (0x70700) /*decimal 460544*/

#define GETH_PORT1_TRANSMIT_CLK_PERIOD_NS (1.00000)

#define GETH_PORTn_MAC_INT_PRIO (0x3) /*decimal 3*/

#define GETH_PORTn_MAC_INT_TOS (0x0) /*decimal 0*/

#endif /* TC4D_GETH_MAC_CFG_H */
