/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_GETH_DMA_CFG_H
#define TC4D_GETH_DMA_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define GETH_BRDG_PORT0_Rx0_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA0_Link visible

#define GETH_BRDG_PORT0_Rx0_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_DMA7_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA0_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA1_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA2_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA3_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA4_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA5_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA6_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA0_Link visible

#define GETH_BRDG_PORT0_Tx0_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx0_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx1_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx2_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx3_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx4_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx5_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx6_DMA7_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA0_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA1_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA2_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA3_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA4_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA5_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA6_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Tx7_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_DMA7_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA0_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA1_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA2_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA3_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA4_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA5_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA6_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx0_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx1_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx2_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx3_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx4_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx5_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx6_DMA7_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA0_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA1_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA2_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA3_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA4_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA5_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA6_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Tx7_DMA7_Link hidden

#define GETH_DMA_CH0_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH0_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH0_EN (0x1) /*decimal 1*/

#define GETH_DMA_CH0_INTERRUPT_ENABLE (0x41) /*decimal 65*/

#define GETH_DMA_CH0_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH0_INTERRUPT_ENABLE_RIE_ISR Geth_Dma_Ch0_Rx_Isr

#define GETH_DMA_CH0_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH0_INTERRUPT_ENABLE_RX_PRIO (0x5) /*decimal 5*/

#define GETH_DMA_CH0_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH0_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH0_INTERRUPT_ENABLE_TIE_ISR Geth_Dma_Ch0_Tx_Isr

#define GETH_DMA_CH0_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH0_INTERRUPT_ENABLE_TX_PRIO (0x7) /*decimal 7*/

#define GETH_DMA_CH0_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH0_RX_BUFFER_SIZE (0x60E) /*decimal 1550*/

#define GETH_DMA_CH0_RX_CONTROL (0x100C10) /*decimal 1051664*/

#define GETH_DMA_CH0_RX_CONTROL2 (0x7) /*decimal 7*/

#define GETH_DMA_CH0_RX_DESC_LIST_LENGTH (0x8) /*decimal 8*/

#define GETH_DMA_CH0_RX_DESC_LIST_REF rxReadDscrCh0

#define GETH_DMA_CH0_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH0_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH0_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH0_Rx_DisVis hidden

#define GETH_DMA_CH0_Rx_EnVis visible

#define GETH_DMA_CH0_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH0_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH0_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH0_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH0_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH0_TX_CONTROL2 (0x7) /*decimal 7*/

#define GETH_DMA_CH0_TX_DESC_LIST_LENGTH (0x8) /*decimal 8*/

#define GETH_DMA_CH0_TX_DESC_LIST_REF txReadDscrCh0

#define GETH_DMA_CH0_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH0_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH0_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH0_Tx_DisVis hidden

#define GETH_DMA_CH0_Tx_EnVis visible

#define GETH_DMA_CH1_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH1_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH1_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH1_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH1_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH1_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH1_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH1_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH1_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH1_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH1_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH1_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH1_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH1_RX_DESC_LIST_REF rxReadDscrCh1

#define GETH_DMA_CH1_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH1_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH1_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH1_Rx_DisVis visible

#define GETH_DMA_CH1_Rx_EnVis hidden

#define GETH_DMA_CH1_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH1_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH1_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH1_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH1_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH1_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH1_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH1_TX_DESC_LIST_REF txReadDscrCh1

#define GETH_DMA_CH1_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH1_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH1_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH1_Tx_DisVis visible

#define GETH_DMA_CH1_Tx_EnVis hidden

#define GETH_DMA_CH2_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH2_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH2_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH2_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH2_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH2_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH2_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH2_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH2_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH2_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH2_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH2_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH2_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH2_RX_DESC_LIST_REF rxReadDscrCh2

#define GETH_DMA_CH2_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH2_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH2_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH2_Rx_DisVis visible

#define GETH_DMA_CH2_Rx_EnVis hidden

#define GETH_DMA_CH2_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH2_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH2_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH2_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH2_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH2_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH2_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH2_TX_DESC_LIST_REF txReadDscrCh2

#define GETH_DMA_CH2_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH2_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH2_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH2_Tx_DisVis visible

#define GETH_DMA_CH2_Tx_EnVis hidden

#define GETH_DMA_CH3_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH3_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH3_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH3_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH3_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH3_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH3_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH3_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH3_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH3_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH3_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH3_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH3_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH3_RX_DESC_LIST_REF rxReadDscrCh3

#define GETH_DMA_CH3_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH3_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH3_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH3_Rx_DisVis visible

#define GETH_DMA_CH3_Rx_EnVis hidden

#define GETH_DMA_CH3_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH3_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH3_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH3_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH3_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH3_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH3_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH3_TX_DESC_LIST_REF txReadDscrCh3

#define GETH_DMA_CH3_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH3_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH3_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH3_Tx_DisVis visible

#define GETH_DMA_CH3_Tx_EnVis hidden

#define GETH_DMA_CH4_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH4_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH4_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH4_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH4_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH4_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH4_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH4_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH4_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH4_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH4_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH4_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH4_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH4_RX_DESC_LIST_REF rxReadDscrCh4

#define GETH_DMA_CH4_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH4_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH4_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH4_Rx_DisVis visible

#define GETH_DMA_CH4_Rx_EnVis hidden

#define GETH_DMA_CH4_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH4_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH4_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH4_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH4_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH4_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH4_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH4_TX_DESC_LIST_REF txReadDscrCh4

#define GETH_DMA_CH4_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH4_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH4_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH4_Tx_DisVis visible

#define GETH_DMA_CH4_Tx_EnVis hidden

#define GETH_DMA_CH5_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH5_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH5_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH5_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH5_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH5_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH5_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH5_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH5_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH5_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH5_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH5_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH5_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH5_RX_DESC_LIST_REF rxReadDscrCh5

#define GETH_DMA_CH5_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH5_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH5_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH5_Rx_DisVis visible

#define GETH_DMA_CH5_Rx_EnVis hidden

#define GETH_DMA_CH5_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH5_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH5_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH5_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH5_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH5_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH5_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH5_TX_DESC_LIST_REF txReadDscrCh5

#define GETH_DMA_CH5_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH5_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH5_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH5_Tx_DisVis visible

#define GETH_DMA_CH5_Tx_EnVis hidden

#define GETH_DMA_CH6_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH6_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH6_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH6_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH6_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH6_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH6_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH6_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH6_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH6_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH6_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH6_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH6_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH6_RX_DESC_LIST_REF rxReadDscrCh6

#define GETH_DMA_CH6_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH6_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH6_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH6_Rx_DisVis visible

#define GETH_DMA_CH6_Rx_EnVis hidden

#define GETH_DMA_CH6_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH6_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH6_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH6_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH6_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH6_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH6_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH6_TX_DESC_LIST_REF txReadDscrCh6

#define GETH_DMA_CH6_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH6_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH6_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH6_Tx_DisVis visible

#define GETH_DMA_CH6_Tx_EnVis hidden

#define GETH_DMA_CH7_CDES3_VT (0x0) /*decimal 0*/

#define GETH_DMA_CH7_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_CH7_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH7_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define GETH_DMA_CH7_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH7_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH7_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define GETH_DMA_CH7_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define GETH_DMA_CH7_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define GETH_DMA_CH7_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH7_RX_CONTROL (0x100BD0) /*decimal 1051600*/

#define GETH_DMA_CH7_RX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH7_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH7_RX_DESC_LIST_REF rxReadDscrCh7

#define GETH_DMA_CH7_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH7_RX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH7_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH7_Rx_DisVis visible

#define GETH_DMA_CH7_Rx_EnVis hidden

#define GETH_DMA_CH7_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define GETH_DMA_CH7_TDES2_VTIR (0x0) /*decimal 0*/

#define GETH_DMA_CH7_TS_EN (0x0) /*decimal 0*/

#define GETH_DMA_CH7_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define GETH_DMA_CH7_TX_CONTROL (0x100000) /*decimal 1048576*/

#define GETH_DMA_CH7_TX_CONTROL2 (0x3) /*decimal 3*/

#define GETH_DMA_CH7_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define GETH_DMA_CH7_TX_DESC_LIST_REF txReadDscrCh7

#define GETH_DMA_CH7_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define GETH_DMA_CH7_TX_DESC_TYPE (0x0) /*decimal 0*/

#define GETH_DMA_CH7_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define GETH_DMA_CH7_Tx_DisVis visible

#define GETH_DMA_CH7_Tx_EnVis hidden

#define GETH_DMA_DESC_TYPE_ENHANCED (2)

#define GETH_DMA_DESC_TYPE_NORMAL (0)

#define GETH_DMA_DESC_TYPE_NORMAL_CONTEXT (1)

#define GETH_DMA_MODE (0x1) /*decimal 1*/

#define GETH_DMA_PORT_SELECTION_CH0 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH1 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH2 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH3 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH4 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH5 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH6 (0x0) /*decimal 0*/

#define GETH_DMA_PORT_SELECTION_CH7 (0x0) /*decimal 0*/

#define GETH_DMA_RXCH0_EN (0x1) /*decimal 1*/

#define GETH_DMA_RXCH1_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH2_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH3_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH4_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH5_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH6_EN (0x0) /*decimal 0*/

#define GETH_DMA_RXCH7_EN (0x0) /*decimal 0*/

#define GETH_DMA_RX_EDMA_CONTROL (0x0) /*decimal 0*/

#define GETH_DMA_SYSBUS_MODE (0x1008) /*decimal 4104*/

#define GETH_DMA_SYSBUS_MODE_BLENx (0x10) /*decimal 16*/

#define GETH_DMA_TXCH0_EN (0x1) /*decimal 1*/

#define GETH_DMA_TXCH1_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH2_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH3_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH4_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH5_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH6_EN (0x0) /*decimal 0*/

#define GETH_DMA_TXCH7_EN (0x0) /*decimal 0*/

#define GETH_DMA_TX_EDMA_CONTROL (0x0) /*decimal 0*/

#endif /* TC4D_GETH_DMA_CFG_H */
