/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_LETH_DMA_CFG_H
#define TC4D_LETH_DMA_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define LETH_DMA_CH0_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH0_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH0_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH0_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH0_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH0_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH0_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH0_INTERRUPT_ENABLE_TX_PRIO (0x6) /*decimal 6*/

#define LETH_DMA_CH0_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH0_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH0_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH0_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH0_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH0_RX_DESC_LIST_REF lethRxReadDscrCh0

#define LETH_DMA_CH0_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH0_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH0_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH0_Rx_DisVis visible

#define LETH_DMA_CH0_Rx_EnVis hidden

#define LETH_DMA_CH0_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH0_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH0_TX_DESC_LIST_REF lethTxReadDscrCh0

#define LETH_DMA_CH0_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH0_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH0_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH0_Tx_DisVis visible

#define LETH_DMA_CH0_Tx_EnVis hidden

#define LETH_DMA_CH1_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH1_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH1_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH1_INTERRUPT_ENABLE (0x1) /*decimal 1*/

#define LETH_DMA_CH1_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH1_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH1_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH1_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH1_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH1_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH1_INTERRUPT_ENABLE_TIE_ISR Leth_DMA_Ch1_Tx_Isr

#define LETH_DMA_CH1_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH1_INTERRUPT_ENABLE_TX_PRIO (0x6) /*decimal 6*/

#define LETH_DMA_CH1_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH1_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH1_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH1_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH1_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH1_RX_DESC_LIST_REF lethRxReadDscrCh1

#define LETH_DMA_CH1_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH1_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH1_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH1_Rx_DisVis visible

#define LETH_DMA_CH1_Rx_EnVis hidden

#define LETH_DMA_CH1_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH1_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TX_DESC_LIST_LENGTH (0x8) /*decimal 8*/

#define LETH_DMA_CH1_TX_DESC_LIST_REF lethTxReadDscrCh1

#define LETH_DMA_CH1_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH1_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH1_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH1_Tx_DisVis visible

#define LETH_DMA_CH1_Tx_EnVis hidden

#define LETH_DMA_CH2_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH2_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH2_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH2_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH2_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH2_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH2_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH2_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH2_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH2_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH2_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH2_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH2_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH2_RX_DESC_LIST_REF lethRxReadDscrCh2

#define LETH_DMA_CH2_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH2_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH2_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH2_Rx_DisVis visible

#define LETH_DMA_CH2_Rx_EnVis hidden

#define LETH_DMA_CH2_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH2_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH2_TX_DESC_LIST_REF lethTxReadDscrCh2

#define LETH_DMA_CH2_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH2_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH2_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH2_Tx_DisVis visible

#define LETH_DMA_CH2_Tx_EnVis hidden

#define LETH_DMA_CH3_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH3_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH3_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH3_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH3_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH3_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH3_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH3_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH3_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH3_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH3_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH3_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH3_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH3_RX_DESC_LIST_REF lethRxReadDscrCh3

#define LETH_DMA_CH3_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH3_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH3_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH3_Rx_DisVis visible

#define LETH_DMA_CH3_Rx_EnVis hidden

#define LETH_DMA_CH3_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH3_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH3_TX_DESC_LIST_REF lethTxReadDscrCh3

#define LETH_DMA_CH3_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH3_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH3_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH3_Tx_DisVis visible

#define LETH_DMA_CH3_Tx_EnVis hidden

#define LETH_DMA_CH4_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH4_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH4_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH4_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH4_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH4_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH4_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH4_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH4_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH4_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH4_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH4_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH4_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH4_RX_DESC_LIST_REF lethRxReadDscrCh4

#define LETH_DMA_CH4_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH4_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH4_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH4_Rx_DisVis visible

#define LETH_DMA_CH4_Rx_EnVis hidden

#define LETH_DMA_CH4_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH4_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH4_TX_DESC_LIST_REF lethTxReadDscrCh4

#define LETH_DMA_CH4_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH4_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH4_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH4_Tx_DisVis visible

#define LETH_DMA_CH4_Tx_EnVis hidden

#define LETH_DMA_CH5_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH5_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH5_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH5_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH5_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH5_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH5_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH5_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH5_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH5_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH5_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH5_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH5_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH5_RX_DESC_LIST_REF lethRxReadDscrCh5

#define LETH_DMA_CH5_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH5_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH5_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH5_Rx_DisVis visible

#define LETH_DMA_CH5_Rx_EnVis hidden

#define LETH_DMA_CH5_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH5_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH5_TX_DESC_LIST_REF lethTxReadDscrCh5

#define LETH_DMA_CH5_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH5_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH5_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH5_Tx_DisVis visible

#define LETH_DMA_CH5_Tx_EnVis hidden

#define LETH_DMA_CH6_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH6_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH6_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH6_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH6_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH6_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH6_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH6_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH6_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH6_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH6_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH6_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH6_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH6_RX_DESC_LIST_REF lethRxReadDscrCh6

#define LETH_DMA_CH6_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH6_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH6_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH6_Rx_DisVis visible

#define LETH_DMA_CH6_Rx_EnVis hidden

#define LETH_DMA_CH6_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH6_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH6_TX_DESC_LIST_REF lethTxReadDscrCh6

#define LETH_DMA_CH6_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH6_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH6_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH6_Tx_DisVis visible

#define LETH_DMA_CH6_Tx_EnVis hidden

#define LETH_DMA_CH7_CDES3_VT (0x0) /*decimal 0*/

#define LETH_DMA_CH7_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH7_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH7_INTERRUPT_ENABLE (0x0) /*decimal 0*/

#define LETH_DMA_CH7_INTERRUPT_ENABLE_RBUE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_RIE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_RSE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_RX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH7_INTERRUPT_ENABLE_RX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH7_INTERRUPT_ENABLE_TBUE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_TIE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_TXSE_ISR enter callback function here

#define LETH_DMA_CH7_INTERRUPT_ENABLE_TX_PRIO (0x0) /*decimal 0*/

#define LETH_DMA_CH7_INTERRUPT_ENABLE_TX_TOS (0x0) /*decimal 0*/

#define LETH_DMA_CH7_RX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH7_RX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH7_RX_CONTROL2 (0x3) /*decimal 3*/

#define LETH_DMA_CH7_RX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH7_RX_DESC_LIST_REF lethRxReadDscrCh7

#define LETH_DMA_CH7_RX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH7_RX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH7_Rx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH7_Rx_DisVis visible

#define LETH_DMA_CH7_Rx_EnVis hidden

#define LETH_DMA_CH7_Slot_Function_Control_Status (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TDES2_VTIR (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TS_EN (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TX_BUFFER_SIZE (0x5EE) /*decimal 1518*/

#define LETH_DMA_CH7_TX_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TX_CONTROL2 (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TX_DESC_LIST_LENGTH (0x4) /*decimal 4*/

#define LETH_DMA_CH7_TX_DESC_LIST_REF lethTxReadDscrCh7

#define LETH_DMA_CH7_TX_DESC_LOCATION_IDX (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TX_DESC_SAIC (0x0) /*decimal 0*/

#define LETH_DMA_CH7_TX_DESC_TYPE (0x0) /*decimal 0*/

#define LETH_DMA_CH7_Tx_Connect_Cnt (0x0) /*decimal 0*/

#define LETH_DMA_CH7_Tx_DisVis visible

#define LETH_DMA_CH7_Tx_EnVis hidden

#define LETH_DMA_DESC_TYPE_NORMAL (0)

#define LETH_DMA_DESC_TYPE_NORMAL_CONTEXT (1)

#define LETH_DMA_MODE (0x1) /*decimal 1*/

#define LETH_DMA_RXCH0_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH1_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH2_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH3_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH4_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH5_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH6_EN (0x0) /*decimal 0*/

#define LETH_DMA_RXCH7_EN (0x0) /*decimal 0*/

#define LETH_DMA_RX_EDMA_CONTROL (0x0) /*decimal 0*/

#define LETH_DMA_SYSBUS_MODE (0x1008) /*decimal 4104*/

#define LETH_DMA_SYSBUS_MODE_BLENx (0x10) /*decimal 16*/

#define LETH_DMA_TXCH0_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH1_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH2_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH3_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH4_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH5_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH6_EN (0x0) /*decimal 0*/

#define LETH_DMA_TXCH7_EN (0x0) /*decimal 0*/

#define LETH_DMA_TX_EDMA_CONTROL (0x0) /*decimal 0*/

#endif /* TC4D_LETH_DMA_CFG_H */
