/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_GETH_BRDG_CFG_H
#define TC4D_GETH_BRDG_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define GETH_BRDG_PORT0_CH0_FWD_CONT_EN (0x1) /*decimal 1*/

#define GETH_BRDG_PORT0_CH1_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH2_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH3_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH4_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH5_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH6_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_CH7_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT0_Rx0_DisVis hidden

#define GETH_BRDG_PORT0_Rx0_EnVis visible

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx0_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx0_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx1_DisVis visible

#define GETH_BRDG_PORT0_Rx1_EnVis hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx1_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx1_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx2_DisVis visible

#define GETH_BRDG_PORT0_Rx2_EnVis hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx2_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx2_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx3_DisVis visible

#define GETH_BRDG_PORT0_Rx3_EnVis hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx3_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx3_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx4_DisVis visible

#define GETH_BRDG_PORT0_Rx4_EnVis hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx4_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx4_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx5_DisVis visible

#define GETH_BRDG_PORT0_Rx5_EnVis hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx5_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx5_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx6_DisVis visible

#define GETH_BRDG_PORT0_Rx6_EnVis hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx6_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx6_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Rx7_DisVis visible

#define GETH_BRDG_PORT0_Rx7_EnVis hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx0_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx1_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx2_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx3_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx4_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx5_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx6_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT0_Rx7_PORT1_Tx7_Link hidden

#define GETH_BRDG_PORT0_Rx7_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx0_DisVis hidden

#define GETH_BRDG_PORT0_Tx0_EnVis visible

#define GETH_BRDG_PORT0_Tx0_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx1_DisVis visible

#define GETH_BRDG_PORT0_Tx1_EnVis hidden

#define GETH_BRDG_PORT0_Tx1_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx2_DisVis visible

#define GETH_BRDG_PORT0_Tx2_EnVis hidden

#define GETH_BRDG_PORT0_Tx2_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx3_DisVis visible

#define GETH_BRDG_PORT0_Tx3_EnVis hidden

#define GETH_BRDG_PORT0_Tx3_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx4_DisVis visible

#define GETH_BRDG_PORT0_Tx4_EnVis hidden

#define GETH_BRDG_PORT0_Tx4_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx5_DisVis visible

#define GETH_BRDG_PORT0_Tx5_EnVis hidden

#define GETH_BRDG_PORT0_Tx5_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx6_DisVis visible

#define GETH_BRDG_PORT0_Tx6_EnVis hidden

#define GETH_BRDG_PORT0_Tx6_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT0_Tx7_DisVis visible

#define GETH_BRDG_PORT0_Tx7_EnVis hidden

#define GETH_BRDG_PORT0_Tx7_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_CH0_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH1_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH2_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH3_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH4_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH5_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH6_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_CH7_FWD_CONT_EN (0x0) /*decimal 0*/

#define GETH_BRDG_PORT1_Rx0_DisVis visible

#define GETH_BRDG_PORT1_Rx0_EnVis hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx0_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx0_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx1_DisVis visible

#define GETH_BRDG_PORT1_Rx1_EnVis hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx1_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx1_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx2_DisVis visible

#define GETH_BRDG_PORT1_Rx2_EnVis hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx2_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx2_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx3_DisVis visible

#define GETH_BRDG_PORT1_Rx3_EnVis hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx3_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx3_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx4_DisVis visible

#define GETH_BRDG_PORT1_Rx4_EnVis hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx4_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx4_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx5_DisVis visible

#define GETH_BRDG_PORT1_Rx5_EnVis hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx5_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx5_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx6_DisVis visible

#define GETH_BRDG_PORT1_Rx6_EnVis hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx6_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx6_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Rx7_DisVis visible

#define GETH_BRDG_PORT1_Rx7_EnVis hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx0_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx0_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx1_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx1_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx2_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx2_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx3_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx3_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx4_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx4_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx5_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx5_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx6_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx6_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx7_Dashed_Link hidden

#define GETH_BRDG_PORT1_Rx7_PORT0_Tx7_Link hidden

#define GETH_BRDG_PORT1_Rx7_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx0_DisVis visible

#define GETH_BRDG_PORT1_Tx0_EnVis hidden

#define GETH_BRDG_PORT1_Tx0_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx1_DisVis visible

#define GETH_BRDG_PORT1_Tx1_EnVis hidden

#define GETH_BRDG_PORT1_Tx1_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx2_DisVis visible

#define GETH_BRDG_PORT1_Tx2_EnVis hidden

#define GETH_BRDG_PORT1_Tx2_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx3_DisVis visible

#define GETH_BRDG_PORT1_Tx3_EnVis hidden

#define GETH_BRDG_PORT1_Tx3_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx4_DisVis visible

#define GETH_BRDG_PORT1_Tx4_EnVis hidden

#define GETH_BRDG_PORT1_Tx4_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx5_DisVis visible

#define GETH_BRDG_PORT1_Tx5_EnVis hidden

#define GETH_BRDG_PORT1_Tx5_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx6_DisVis visible

#define GETH_BRDG_PORT1_Tx6_EnVis hidden

#define GETH_BRDG_PORT1_Tx6_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_BRDG_PORT1_Tx7_DisVis visible

#define GETH_BRDG_PORT1_Tx7_EnVis hidden

#define GETH_BRDG_PORT1_Tx7_TargetDMA (0xFFFFFFFF) /*decimal 4294967295*/

#define GETH_DMA_PORT_SELECTION (0x0) /*decimal 0*/

#define GETH_ECC_CONTROL (0x20) /*decimal 32*/

#define GETH_FORWARD_CONTROL (0x2001003F) /*decimal 536936511*/

#define GETH_FORWARD_CONTROL_MAX_PKT_LENGTH_USER (0x40) /*decimal 64*/

#define GETH_PORT_0_CONTROL (0x1000100) /*decimal 16777472*/

#define GETH_PORT_1_CONTROL (0x0) /*decimal 0*/

#define GETH_RXC_MAP_PORT_0 (0x76543210) /*decimal 1985229328*/

#define GETH_RXC_MAP_PORT_1 (0x76543211) /*decimal 1985229329*/

#define GETH_RXQ_MAP_PORT_0_RXQ0_DMA_MAP (0x0) /*decimal 0*/

#define GETH_RXQ_MAP_PORT_0_RXQ0_FWD_MAP (0x0) /*decimal 0*/

#define GETH_RXQ_MAP_PORT_0_RXQ1_DMA_MAP (0x1) /*decimal 1*/

#define GETH_RXQ_MAP_PORT_0_RXQ1_FWD_MAP (0x1) /*decimal 1*/

#define GETH_RXQ_MAP_PORT_0_RXQ2_DMA_MAP (0x2) /*decimal 2*/

#define GETH_RXQ_MAP_PORT_0_RXQ2_FWD_MAP (0x2) /*decimal 2*/

#define GETH_RXQ_MAP_PORT_0_RXQ3_DMA_MAP (0x3) /*decimal 3*/

#define GETH_RXQ_MAP_PORT_0_RXQ3_FWD_MAP (0x3) /*decimal 3*/

#define GETH_RXQ_MAP_PORT_0_RXQ4_DMA_MAP (0x4) /*decimal 4*/

#define GETH_RXQ_MAP_PORT_0_RXQ4_FWD_MAP (0x4) /*decimal 4*/

#define GETH_RXQ_MAP_PORT_0_RXQ5_DMA_MAP (0x5) /*decimal 5*/

#define GETH_RXQ_MAP_PORT_0_RXQ5_FWD_MAP (0x5) /*decimal 5*/

#define GETH_RXQ_MAP_PORT_0_RXQ6_DMA_MAP (0x6) /*decimal 6*/

#define GETH_RXQ_MAP_PORT_0_RXQ6_FWD_MAP (0x6) /*decimal 6*/

#define GETH_RXQ_MAP_PORT_0_RXQ7_DMA_MAP (0x7) /*decimal 7*/

#define GETH_RXQ_MAP_PORT_0_RXQ7_FWD_MAP (0x7) /*decimal 7*/

#define GETH_RXQ_MAP_PORT_1_RXQ0_DMA_MAP (0x1) /*decimal 1*/

#define GETH_RXQ_MAP_PORT_1_RXQ0_FWD_MAP (0x0) /*decimal 0*/

#define GETH_RXQ_MAP_PORT_1_RXQ1_DMA_MAP (0x1) /*decimal 1*/

#define GETH_RXQ_MAP_PORT_1_RXQ1_FWD_MAP (0x1) /*decimal 1*/

#define GETH_RXQ_MAP_PORT_1_RXQ2_DMA_MAP (0x2) /*decimal 2*/

#define GETH_RXQ_MAP_PORT_1_RXQ2_FWD_MAP (0x2) /*decimal 2*/

#define GETH_RXQ_MAP_PORT_1_RXQ3_DMA_MAP (0x3) /*decimal 3*/

#define GETH_RXQ_MAP_PORT_1_RXQ3_FWD_MAP (0x3) /*decimal 3*/

#define GETH_RXQ_MAP_PORT_1_RXQ4_DMA_MAP (0x4) /*decimal 4*/

#define GETH_RXQ_MAP_PORT_1_RXQ4_FWD_MAP (0x4) /*decimal 4*/

#define GETH_RXQ_MAP_PORT_1_RXQ5_DMA_MAP (0x5) /*decimal 5*/

#define GETH_RXQ_MAP_PORT_1_RXQ5_FWD_MAP (0x5) /*decimal 5*/

#define GETH_RXQ_MAP_PORT_1_RXQ6_DMA_MAP (0x6) /*decimal 6*/

#define GETH_RXQ_MAP_PORT_1_RXQ6_FWD_MAP (0x6) /*decimal 6*/

#define GETH_RXQ_MAP_PORT_1_RXQ7_DMA_MAP (0x7) /*decimal 7*/

#define GETH_RXQ_MAP_PORT_1_RXQ7_FWD_MAP (0x7) /*decimal 7*/

#define GETH_TXQ_MAP_PORT_0 (0x76543210) /*decimal 1985229328*/

#define GETH_TXQ_MAP_PORT_0_TXQ0_DMA_MAP (0x0) /*decimal 0*/

#define GETH_TXQ_MAP_PORT_0_TXQ1_DMA_MAP (0x1) /*decimal 1*/

#define GETH_TXQ_MAP_PORT_0_TXQ2_DMA_MAP (0x2) /*decimal 2*/

#define GETH_TXQ_MAP_PORT_0_TXQ3_DMA_MAP (0x3) /*decimal 3*/

#define GETH_TXQ_MAP_PORT_0_TXQ4_DMA_MAP (0x4) /*decimal 4*/

#define GETH_TXQ_MAP_PORT_0_TXQ5_DMA_MAP (0x5) /*decimal 5*/

#define GETH_TXQ_MAP_PORT_0_TXQ6_DMA_MAP (0x6) /*decimal 6*/

#define GETH_TXQ_MAP_PORT_0_TXQ7_DMA_MAP (0x7) /*decimal 7*/

#define GETH_TXQ_MAP_PORT_1 (0x76543211) /*decimal 1985229329*/

#define GETH_TXQ_MAP_PORT_1_TXQ0_DMA_MAP (0x1) /*decimal 1*/

#define GETH_TXQ_MAP_PORT_1_TXQ1_DMA_MAP (0x1) /*decimal 1*/

#define GETH_TXQ_MAP_PORT_1_TXQ2_DMA_MAP (0x2) /*decimal 2*/

#define GETH_TXQ_MAP_PORT_1_TXQ3_DMA_MAP (0x3) /*decimal 3*/

#define GETH_TXQ_MAP_PORT_1_TXQ4_DMA_MAP (0x4) /*decimal 4*/

#define GETH_TXQ_MAP_PORT_1_TXQ5_DMA_MAP (0x5) /*decimal 5*/

#define GETH_TXQ_MAP_PORT_1_TXQ6_DMA_MAP (0x6) /*decimal 6*/

#define GETH_TXQ_MAP_PORT_1_TXQ7_DMA_MAP (0x7) /*decimal 7*/

#endif /* TC4D_GETH_BRDG_CFG_H */
