/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef ICW_TC4D_BOARD_CFG_H
#define ICW_TC4D_BOARD_CFG_H

/* XML Version 0.1.0 */
#define ICW_XML_VERSION (00100)

#define BOARD_DUT_BOARD_PHY0_MII (0x4) /*decimal 4*/

#define BOARD_DUT_BOARD_PHY1_MII (0x1) /*decimal 1*/

#define BOARD_DUT_BOARD_PHY2_LOCK (0x1) /*decimal 1*/

#define BOARD_DUT_BOARD_PHY2_MII (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY2_RMII_RXCLK (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY2_RMII_RXD0 (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY2_RMII_RXD1 (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY2_RMII_RXDV (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY2_RMII_TXD0 (0x1) /*decimal 1*/

#define BOARD_DUT_BOARD_PHY2_RMII_TXD1 (0x1) /*decimal 1*/

#define BOARD_DUT_BOARD_PHY2_RMII_TXEN (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY3_MII (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY4_MII (0x0) /*decimal 0*/

#define BOARD_DUT_BOARD_PHY5_MII (0x0) /*decimal 0*/

#define BOARD_PHY0_MII (0x4) /*decimal 4*/

#define BOARD_SLECTION (0x1) /*decimal 1*/

#define BOARD_TRIBOARD_PHY0_MII (0x0) /*decimal 0*/

#define BOARD_TRIBOARD_PHY1_MII (0x0) /*decimal 0*/

#endif /* ICW_TC4D_BOARD_CFG_H */
