/**
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 *
 */
#ifndef TC4D_STM_CFG_H
#define TC4D_STM_CFG_H

/* XML Version 0.1.0 */
#define TC4D_XML_VERSION (00100)

#define CLOCK_System_Frequency (0x1DCD6500) /*decimal 500000000*/

#define IFX_CFG_STM0_CALLBACK0_EN_0 (0x0) /*decimal 0*/

#define IFX_CFG_STM0_CALLBACK0_EN_1 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_CALLBACK0_FUNC_0 enter callback function here

#define IFX_CFG_STM0_CALLBACK0_FUNC_1 Board_SysTick_Callback

#define IFX_CFG_STM0_CALLBACK0_MS_0 (0xA) /*decimal 10*/

#define IFX_CFG_STM0_CALLBACK0_MS_1 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_CALLBACK1_EN_0 (0x0) /*decimal 0*/

#define IFX_CFG_STM0_CALLBACK1_EN_1 (0x0) /*decimal 0*/

#define IFX_CFG_STM0_CALLBACK1_FUNC_0 enter callback function here

#define IFX_CFG_STM0_CALLBACK1_FUNC_1 enter callback here

#define IFX_CFG_STM0_CALLBACK1_MS_0 (0x64) /*decimal 100*/

#define IFX_CFG_STM0_CALLBACK1_MS_1 (0x64) /*decimal 100*/

#define IFX_CFG_STM0_CALLBACK2_EN_0 (0x0) /*decimal 0*/

#define IFX_CFG_STM0_CALLBACK2_EN_1 (0x0) /*decimal 0*/

#define IFX_CFG_STM0_CALLBACK2_FUNC_0 enter callback function here

#define IFX_CFG_STM0_CALLBACK2_FUNC_1 enter callback here

#define IFX_CFG_STM0_CALLBACK2_MS_0 (0x3E8) /*decimal 1000*/

#define IFX_CFG_STM0_CALLBACK2_MS_1 (0x3E8) /*decimal 1000*/

#define IFX_CFG_STM0_ENABLE_0 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_ENABLE_1 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_INTERRUPT_PRIO_0 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_INTERRUPT_PRIO_1 (0x2) /*decimal 2*/

#define IFX_CFG_STM0_INTERVAL_MS_0 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_INTERVAL_MS_1 (0x1) /*decimal 1*/

#define IFX_CFG_STM0_TICKS_PER_MS_0 (0x7A120) /*decimal 500000*/

#define IFX_CFG_STM0_TICKS_PER_MS_1 (0x7A120) /*decimal 500000*/

#endif /* TC4D_STM_CFG_H */
